// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mraft.proto

package mraft

import (
	"fmt"
	"math"

	raftpb "github.com/coreos/etcd/raft/raftpb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"

	metapb "github.com/deepfabric/elasticell/pkg/pb/metapb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SnapshotState int32

const (
	Accept   SnapshotState = 0
	Reject   SnapshotState = 1
	Received SnapshotState = 2
)

var SnapshotState_name = map[int32]string{
	0: "Accept",
	1: "Reject",
	2: "Received",
}

var SnapshotState_value = map[string]int32{
	"Accept":   0,
	"Reject":   1,
	"Received": 2,
}

func (x SnapshotState) Enum() *SnapshotState { _ = "STUB: not implemented"; return nil }

func (x SnapshotState) String() string { _ = "STUB: not implemented"; return "" }

func (x *SnapshotState) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

func (SnapshotState) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type PeerState int32

const (
	Normal    PeerState = 0
	Applying  PeerState = 1
	Tombstone PeerState = 2
)

var PeerState_name = map[int32]string{
	0: "Normal",
	1: "Applying",
	2: "Tombstone",
}

var PeerState_value = map[string]int32{
	"Normal":    0,
	"Applying":  1,
	"Tombstone": 2,
}

func (x PeerState) Enum() *PeerState { _ = "STUB: not implemented"; return nil }

func (x PeerState) String() string { _ = "STUB: not implemented"; return "" }

func (x *PeerState) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

func (PeerState) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type RaftMessage struct {
	CellID    uint64           `protobuf:"varint,1,opt,name=cellID" json:"cellID"`
	FromPeer  metapb.Peer      `protobuf:"bytes,2,opt,name=fromPeer" json:"fromPeer"`
	ToPeer    metapb.Peer      `protobuf:"bytes,3,opt,name=toPeer" json:"toPeer"`
	Message   raftpb.Message   `protobuf:"bytes,4,opt,name=message" json:"message"`
	CellEpoch metapb.CellEpoch `protobuf:"bytes,5,opt,name=cellEpoch" json:"cellEpoch"`
	// true means to_peer is a tombstone peer and it should remove itself.
	IsTombstone bool `protobuf:"varint,6,opt,name=isTombstone" json:"isTombstone"`
	// Cell key range [start_key, end_key).
	Start                []byte   `protobuf:"bytes,7,opt,name=start" json:"start,omitempty"`
	End                  []byte   `protobuf:"bytes,8,opt,name=end" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftMessage proto.InternalMessageInfo

func (m *RaftMessage) GetCellID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *RaftMessage) GetFromPeer() metapb.Peer {
	_ = "STUB: not implemented"
	return *new(metapb.Peer)
}

func (m *RaftMessage) GetToPeer() metapb.Peer { _ = "STUB: not implemented"; return *new(metapb.Peer) }

func (m *RaftMessage) GetMessage() raftpb.Message {
	_ = "STUB: not implemented"
	return *new(raftpb.Message)
}

func (m *RaftMessage) GetCellEpoch() metapb.CellEpoch {
	_ = "STUB: not implemented"
	return *new(metapb.CellEpoch)
}

func (m *RaftMessage) GetIsTombstone() bool { _ = "STUB: not implemented"; return false }

func (m *RaftMessage) GetStart() []byte { _ = "STUB: not implemented"; return nil }

func (m *RaftMessage) GetEnd() []byte { _ = "STUB: not implemented"; return nil }

type StoreIdent struct {
	ClusterID            uint64   `protobuf:"varint,1,opt,name=clusterID" json:"clusterID"`
	StoreID              uint64   `protobuf:"varint,2,opt,name=storeID" json:"storeID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreIdent) Reset()                    { _ = "STUB: not implemented"; return }
func (m *StoreIdent) String() string            { _ = "STUB: not implemented"; return "" }
func (*StoreIdent) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*StoreIdent) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *StoreIdent) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreIdent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StoreIdent) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StoreIdent) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StoreIdent) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StoreIdent proto.InternalMessageInfo

func (m *StoreIdent) GetClusterID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *StoreIdent) GetStoreID() uint64 { _ = "STUB: not implemented"; return 0 }

type ACKMessage struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq" json:"seq"`
	To                   uint64   `protobuf:"varint,2,opt,name=to" json:"to"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACKMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ACKMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*ACKMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ACKMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ACKMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ACKMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ACKMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ACKMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ACKMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ACKMessage proto.InternalMessageInfo

func (m *ACKMessage) GetSeq() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *ACKMessage) GetTo() uint64 { _ = "STUB: not implemented"; return 0 }

type SnapshotMessageHeader struct {
	Cell                 metapb.Cell `protobuf:"bytes,1,opt,name=cell" json:"cell"`
	FromPeer             metapb.Peer `protobuf:"bytes,2,opt,name=fromPeer" json:"fromPeer"`
	ToPeer               metapb.Peer `protobuf:"bytes,3,opt,name=toPeer" json:"toPeer"`
	Term                 uint64      `protobuf:"varint,4,opt,name=term" json:"term"`
	Index                uint64      `protobuf:"varint,5,opt,name=index" json:"index"`
	Seq                  uint64      `protobuf:"varint,6,opt,name=seq" json:"seq"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SnapshotMessageHeader) Reset()         { _ = "STUB: not implemented"; return }
func (m *SnapshotMessageHeader) String() string { _ = "STUB: not implemented"; return "" }
func (*SnapshotMessageHeader) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SnapshotMessageHeader) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotMessageHeader) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SnapshotMessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotMessageHeader) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SnapshotMessageHeader) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMessageHeader) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SnapshotMessageHeader proto.InternalMessageInfo

func (m *SnapshotMessageHeader) GetCell() metapb.Cell {
	_ = "STUB: not implemented"
	return *new(metapb.Cell)
}

func (m *SnapshotMessageHeader) GetFromPeer() metapb.Peer {
	_ = "STUB: not implemented"
	return *new(metapb.Peer)
}

func (m *SnapshotMessageHeader) GetToPeer() metapb.Peer {
	_ = "STUB: not implemented"
	return *new(metapb.Peer)
}

func (m *SnapshotMessageHeader) GetTerm() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMessageHeader) GetIndex() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMessageHeader) GetSeq() uint64 { _ = "STUB: not implemented"; return 0 }

type SnapshotMessage struct {
	Header               SnapshotMessageHeader `protobuf:"bytes,1,opt,name=header" json:"header"`
	Chunk                *SnapshotChunkMessage `protobuf:"bytes,2,opt,name=chunk" json:"chunk,omitempty"`
	Ack                  *SnapshotAckMessage   `protobuf:"bytes,3,opt,name=ack" json:"ack,omitempty"`
	Ask                  *SnapshotAskMessage   `protobuf:"bytes,4,opt,name=ask" json:"ask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SnapshotMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SnapshotMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*SnapshotMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SnapshotMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SnapshotMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SnapshotMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SnapshotMessage proto.InternalMessageInfo

func (m *SnapshotMessage) GetHeader() SnapshotMessageHeader {
	_ = "STUB: not implemented"
	return *new(SnapshotMessageHeader)
}

func (m *SnapshotMessage) GetChunk() *SnapshotChunkMessage { _ = "STUB: not implemented"; return nil }

func (m *SnapshotMessage) GetAck() *SnapshotAckMessage { _ = "STUB: not implemented"; return nil }

func (m *SnapshotMessage) GetAsk() *SnapshotAskMessage { _ = "STUB: not implemented"; return nil }

type SnapshotChunkMessage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	First                bool     `protobuf:"varint,2,opt,name=first" json:"first"`
	Last                 bool     `protobuf:"varint,3,opt,name=last" json:"last"`
	FileSize             uint64   `protobuf:"varint,4,opt,name=fileSize" json:"fileSize"`
	CheckSum             uint64   `protobuf:"varint,5,opt,name=checkSum" json:"checkSum"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotChunkMessage) Reset()         { _ = "STUB: not implemented"; return }
func (m *SnapshotChunkMessage) String() string { _ = "STUB: not implemented"; return "" }
func (*SnapshotChunkMessage) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SnapshotChunkMessage) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotChunkMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotChunkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotChunkMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SnapshotChunkMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotChunkMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SnapshotChunkMessage proto.InternalMessageInfo

func (m *SnapshotChunkMessage) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (m *SnapshotChunkMessage) GetFirst() bool { _ = "STUB: not implemented"; return false }

func (m *SnapshotChunkMessage) GetLast() bool { _ = "STUB: not implemented"; return false }

func (m *SnapshotChunkMessage) GetFileSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotChunkMessage) GetCheckSum() uint64 { _ = "STUB: not implemented"; return 0 }

type SnapshotAckMessage struct {
	Ack                  SnapshotState `protobuf:"varint,1,opt,name=ack,enum=mraft.SnapshotState" json:"ack"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SnapshotAckMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SnapshotAckMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*SnapshotAckMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SnapshotAckMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SnapshotAckMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotAckMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotAckMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SnapshotAckMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotAckMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SnapshotAckMessage proto.InternalMessageInfo

func (m *SnapshotAckMessage) GetAck() SnapshotState {
	_ = "STUB: not implemented"
	return *new(SnapshotState)
}

type SnapshotAskMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotAskMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SnapshotAskMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*SnapshotAskMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SnapshotAskMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SnapshotAskMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotAskMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotAskMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SnapshotAskMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotAskMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SnapshotAskMessage proto.InternalMessageInfo

type CellLocalState struct {
	State                PeerState   `protobuf:"varint,1,opt,name=state,enum=mraft.PeerState" json:"state"`
	Cell                 metapb.Cell `protobuf:"bytes,2,opt,name=cell" json:"cell"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CellLocalState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CellLocalState) String() string            { _ = "STUB: not implemented"; return "" }
func (*CellLocalState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CellLocalState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CellLocalState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CellLocalState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CellLocalState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CellLocalState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CellLocalState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CellLocalState proto.InternalMessageInfo

func (m *CellLocalState) GetState() PeerState { _ = "STUB: not implemented"; return *new(PeerState) }

func (m *CellLocalState) GetCell() metapb.Cell { _ = "STUB: not implemented"; return *new(metapb.Cell) }

type RaftLocalState struct {
	HardState            raftpb.HardState `protobuf:"bytes,1,opt,name=hardState" json:"hardState"`
	LastIndex            uint64           `protobuf:"varint,2,opt,name=lastIndex" json:"lastIndex"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RaftLocalState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftLocalState) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftLocalState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftLocalState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftLocalState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftLocalState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftLocalState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftLocalState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftLocalState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftLocalState proto.InternalMessageInfo

func (m *RaftLocalState) GetHardState() raftpb.HardState {
	_ = "STUB: not implemented"
	return *new(raftpb.HardState)
}

func (m *RaftLocalState) GetLastIndex() uint64 { _ = "STUB: not implemented"; return 0 }

type RaftTruncatedState struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index" json:"index"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term" json:"term"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftTruncatedState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftTruncatedState) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftTruncatedState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftTruncatedState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftTruncatedState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftTruncatedState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftTruncatedState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftTruncatedState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftTruncatedState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftTruncatedState proto.InternalMessageInfo

func (m *RaftTruncatedState) GetIndex() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *RaftTruncatedState) GetTerm() uint64 { _ = "STUB: not implemented"; return 0 }

type RaftApplyState struct {
	AppliedIndex         uint64             `protobuf:"varint,1,opt,name=applied_index,json=appliedIndex" json:"applied_index"`
	TruncatedState       RaftTruncatedState `protobuf:"bytes,2,opt,name=truncated_state,json=truncatedState" json:"truncated_state"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RaftApplyState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftApplyState) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftApplyState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftApplyState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftApplyState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftApplyState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftApplyState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftApplyState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftApplyState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftApplyState proto.InternalMessageInfo

func (m *RaftApplyState) GetAppliedIndex() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *RaftApplyState) GetTruncatedState() RaftTruncatedState {
	_ = "STUB: not implemented"
	return *new(RaftTruncatedState)
}

func init() {
	proto.RegisterEnum("mraft.SnapshotState", SnapshotState_name, SnapshotState_value)
	proto.RegisterEnum("mraft.PeerState", PeerState_name, PeerState_value)
	proto.RegisterType((*RaftMessage)(nil), "mraft.RaftMessage")
	proto.RegisterType((*StoreIdent)(nil), "mraft.StoreIdent")
	proto.RegisterType((*ACKMessage)(nil), "mraft.ACKMessage")
	proto.RegisterType((*SnapshotMessageHeader)(nil), "mraft.SnapshotMessageHeader")
	proto.RegisterType((*SnapshotMessage)(nil), "mraft.SnapshotMessage")
	proto.RegisterType((*SnapshotChunkMessage)(nil), "mraft.SnapshotChunkMessage")
	proto.RegisterType((*SnapshotAckMessage)(nil), "mraft.SnapshotAckMessage")
	proto.RegisterType((*SnapshotAskMessage)(nil), "mraft.SnapshotAskMessage")
	proto.RegisterType((*CellLocalState)(nil), "mraft.CellLocalState")
	proto.RegisterType((*RaftLocalState)(nil), "mraft.RaftLocalState")
	proto.RegisterType((*RaftTruncatedState)(nil), "mraft.RaftTruncatedState")
	proto.RegisterType((*RaftApplyState)(nil), "mraft.RaftApplyState")
}

func init() { proto.RegisterFile("mraft.proto", fileDescriptor_5a9bc23a653d4ba8) }

var fileDescriptor_5a9bc23a653d4ba8 = []byte{
	// 807 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcb, 0x6e, 0xdb, 0x38,
	0x14, 0xb5, 0xe4, 0x47, 0xec, 0x6b, 0xc7, 0xd1, 0x70, 0x3c, 0x03, 0x4d, 0x26, 0xf0, 0x18, 0x5a,
	0x04, 0x9e, 0x34, 0xb5, 0xd1, 0xa0, 0xd9, 0x64, 0xe7, 0x24, 0x05, 0x92, 0xbe, 0x10, 0xd8, 0xd9,
	0x07, 0x34, 0x45, 0xdb, 0xaa, 0x25, 0x51, 0x95, 0xe8, 0xa2, 0xed, 0xbe, 0xff, 0xd0, 0x0f, 0xe8,
	0x7f, 0x74, 0x9b, 0x65, 0xd6, 0x5d, 0x14, 0x6d, 0xba, 0xea, 0x5f, 0x14, 0xa4, 0x48, 0xf9, 0x95,
	0x76, 0xd7, 0x8d, 0x4d, 0x9d, 0x7b, 0xee, 0xe5, 0xb9, 0x2f, 0x42, 0x35, 0x88, 0xf1, 0x88, 0x77,
	0xa2, 0x98, 0x71, 0x86, 0x8a, 0xf2, 0x63, 0xfb, 0xcf, 0x80, 0x72, 0x1c, 0x0d, 0xbb, 0xe9, 0x5f,
	0x6a, 0xdb, 0x6e, 0x8c, 0xd9, 0x98, 0xc9, 0x63, 0x57, 0x9c, 0x14, 0x7a, 0x7f, 0xec, 0xf1, 0xc9,
	0x6c, 0xd8, 0x21, 0x2c, 0xe8, 0x12, 0x16, 0x53, 0x96, 0x74, 0x29, 0x27, 0x6e, 0x57, 0xc4, 0x91,
	0x3f, 0xd1, 0xb0, 0x3b, 0xbf, 0xc0, 0xf9, 0x68, 0x42, 0xb5, 0x8f, 0x47, 0xfc, 0x19, 0x4d, 0x12,
	0x3c, 0xa6, 0x68, 0x07, 0x4a, 0x84, 0xfa, 0xfe, 0xf9, 0xa9, 0x6d, 0xb4, 0x8c, 0x76, 0xe1, 0xb8,
	0x70, 0xfd, 0xf9, 0xbf, 0x5c, 0x5f, 0x61, 0xa8, 0x03, 0xe5, 0x51, 0xcc, 0x82, 0x0b, 0x4a, 0x63,
	0xdb, 0x6c, 0x19, 0xed, 0xea, 0x41, 0xad, 0xa3, 0x34, 0x09, 0x4c, 0xb1, 0x33, 0x0e, 0xda, 0x83,
	0x12, 0x67, 0x92, 0x9d, 0xff, 0x29, 0x5b, 0x31, 0x50, 0x17, 0x36, 0x82, 0x54, 0x84, 0x5d, 0x90,
	0xe4, 0xad, 0x4e, 0x2a, 0xb7, 0xa3, 0xb4, 0x29, 0xbe, 0x66, 0xa1, 0x43, 0xa8, 0x08, 0x59, 0x8f,
	0x22, 0x46, 0x26, 0x76, 0x51, 0xba, 0xfc, 0xa1, 0xe3, 0x9f, 0x68, 0x83, 0x72, 0x9a, 0x33, 0xd1,
	0x2e, 0x54, 0xbd, 0xe4, 0x92, 0x05, 0xc3, 0x84, 0xb3, 0x90, 0xda, 0xa5, 0x96, 0xd1, 0x2e, 0x2b,
	0xd6, 0xa2, 0x01, 0x35, 0xa0, 0x98, 0x70, 0x1c, 0x73, 0x7b, 0xa3, 0x65, 0xb4, 0x6b, 0xfd, 0xf4,
	0x03, 0x59, 0x90, 0xa7, 0xa1, 0x6b, 0x97, 0x25, 0x26, 0x8e, 0xce, 0x05, 0xc0, 0x80, 0xb3, 0x98,
	0x9e, 0xbb, 0x34, 0xe4, 0xc8, 0x81, 0x0a, 0xf1, 0x67, 0x09, 0xa7, 0xf1, 0x4a, 0x09, 0xe7, 0x30,
	0x6a, 0xc2, 0x46, 0x22, 0x3d, 0x4e, 0x65, 0x11, 0x35, 0x43, 0x83, 0xce, 0x11, 0x40, 0xef, 0xe4,
	0x89, 0xee, 0xc8, 0xdf, 0x90, 0x4f, 0xe8, 0xcb, 0xa5, 0x58, 0x02, 0x40, 0x0d, 0x30, 0x39, 0x5b,
	0x0a, 0x60, 0x72, 0xe6, 0x7c, 0x37, 0xe0, 0xaf, 0x41, 0x88, 0xa3, 0x64, 0xc2, 0x74, 0x4f, 0xcf,
	0x28, 0x76, 0x69, 0x8c, 0x76, 0xa1, 0x20, 0x8a, 0x20, 0x03, 0x2d, 0x74, 0x42, 0x54, 0x4a, 0xf9,
	0x4b, 0xfb, 0x6f, 0xed, 0xb1, 0x0d, 0x05, 0x4e, 0xe3, 0x40, 0x36, 0x58, 0xab, 0x96, 0x08, 0xda,
	0x86, 0xa2, 0x17, 0xba, 0xf4, 0xb5, 0x6c, 0xa4, 0x36, 0xa5, 0x90, 0xae, 0x40, 0x69, 0xa5, 0x02,
	0xce, 0x27, 0x03, 0xb6, 0x56, 0x72, 0x45, 0x47, 0x50, 0x9a, 0xc8, 0x7c, 0x55, 0x9e, 0x3b, 0x9d,
	0x74, 0x9d, 0xee, 0xac, 0x89, 0x56, 0x97, 0x7a, 0xa0, 0x07, 0x50, 0x24, 0x93, 0x59, 0x38, 0x55,
	0x69, 0xff, 0xbb, 0xe2, 0x7a, 0x22, 0x6c, 0xca, 0xbf, 0x9f, 0x32, 0xd1, 0x3d, 0xc8, 0x63, 0x32,
	0x55, 0x99, 0xff, 0xb3, 0xe2, 0xd0, 0x23, 0x19, 0x5d, 0xb0, 0x24, 0x39, 0x99, 0xaa, 0xe9, 0x5e,
	0x23, 0x27, 0x0b, 0xe4, 0x64, 0xea, 0x7c, 0x30, 0xa0, 0x71, 0xd7, 0xcd, 0x08, 0x41, 0xc1, 0xc5,
	0x1c, 0xcb, 0xfc, 0x6a, 0x7d, 0x79, 0x16, 0xd5, 0x1b, 0x79, 0x71, 0xc2, 0xa5, 0x72, 0x3d, 0xcd,
	0x29, 0x24, 0x6a, 0xee, 0xe3, 0x84, 0x4b, 0x8d, 0xda, 0x24, 0x11, 0xd4, 0x82, 0xf2, 0xc8, 0xf3,
	0xe9, 0xc0, 0x7b, 0x4b, 0x97, 0x3a, 0x92, 0xa1, 0x82, 0x41, 0x26, 0x94, 0x4c, 0x07, 0xb3, 0x60,
	0xa9, 0x31, 0x19, 0xea, 0x1c, 0x03, 0x5a, 0x4f, 0x17, 0xed, 0xa7, 0x65, 0x11, 0x12, 0xeb, 0x07,
	0x8d, 0x95, 0x4c, 0x07, 0x1c, 0x73, 0xbd, 0xcc, 0x82, 0xe6, 0x34, 0x16, 0x62, 0x64, 0x55, 0x70,
	0x46, 0x50, 0x17, 0xb3, 0xf9, 0x94, 0x11, 0xec, 0x4b, 0x17, 0xb4, 0x2f, 0x37, 0x92, 0x53, 0x15,
	0xd7, 0x52, 0x71, 0xc5, 0x64, 0x2d, 0xc6, 0x4c, 0x49, 0xd9, 0xbc, 0x9b, 0xbf, 0x9e, 0x77, 0x67,
	0x0a, 0x75, 0xf1, 0x00, 0x2e, 0xdc, 0x73, 0x08, 0x95, 0x09, 0x8e, 0xdd, 0x41, 0x76, 0x97, 0x78,
	0x58, 0xd4, 0x5b, 0x74, 0xa6, 0x0d, 0x7a, 0xad, 0x33, 0xa6, 0x58, 0x7d, 0x51, 0xd6, 0x73, 0x39,
	0xc6, 0x8b, 0x7b, 0x39, 0x87, 0x9d, 0xc7, 0x80, 0xc4, 0x65, 0x97, 0xf1, 0x2c, 0x24, 0x98, 0x53,
	0xe5, 0x99, 0x0d, 0xbf, 0xb1, 0x3e, 0xfc, 0x7a, 0x65, 0xcc, 0xd5, 0x95, 0x71, 0xde, 0x19, 0xa9,
	0xf2, 0x5e, 0x14, 0xf9, 0x6f, 0xd2, 0x40, 0xff, 0xc3, 0x26, 0x8e, 0x22, 0xdf, 0xa3, 0xee, 0xd5,
	0x7a, 0xc0, 0x9a, 0x32, 0x49, 0x25, 0xe8, 0x0c, 0xb6, 0xb8, 0x56, 0x71, 0x95, 0x96, 0xd5, 0x5c,
	0x1a, 0xcc, 0x75, 0x9d, 0x2a, 0x4e, 0x9d, 0x2f, 0xa1, 0x7b, 0x87, 0xb0, 0xb9, 0xd4, 0x5a, 0x04,
	0x50, 0xea, 0x11, 0x42, 0x23, 0x6e, 0xe5, 0xc4, 0xb9, 0x4f, 0x5f, 0x50, 0xc2, 0x2d, 0x03, 0xd5,
	0xa0, 0xdc, 0xa7, 0x84, 0x7a, 0xaf, 0xa8, 0x6b, 0x99, 0x7b, 0x0f, 0xa1, 0x92, 0x75, 0x4e, 0xd0,
	0x9e, 0xb3, 0x38, 0xc0, 0xbe, 0x95, 0x13, 0x34, 0x99, 0x92, 0x17, 0x8e, 0x2d, 0x03, 0x6d, 0x42,
	0x25, 0x7b, 0x93, 0x2d, 0xf3, 0xb8, 0x71, 0xf3, 0xb5, 0x99, 0xbb, 0xbe, 0x6d, 0x1a, 0x37, 0xb7,
	0x4d, 0xe3, 0xcb, 0x6d, 0xd3, 0x78, 0xff, 0xad, 0x99, 0xfb, 0x11, 0x00, 0x00, 0xff, 0xff, 0x50,
	0x4d, 0xd8, 0x6e, 0x34, 0x07, 0x00, 0x00,
}

func (m *RaftMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftMessage) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *RaftMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreIdent) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *StoreIdent) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *StoreIdent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ACKMessage) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ACKMessage) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ACKMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotMessageHeader) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotMessageHeader) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotMessageHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotChunkMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotChunkMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotChunkMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotAckMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotAckMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotAckMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotAskMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotAskMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotAskMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CellLocalState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CellLocalState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CellLocalState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftLocalState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftLocalState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftLocalState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftTruncatedState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftTruncatedState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftTruncatedState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftApplyState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftApplyState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftApplyState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintMraft(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *RaftMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreIdent) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ACKMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMessageHeader) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotChunkMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotAckMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotAskMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CellLocalState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftLocalState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftTruncatedState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftApplyState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovMraft(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozMraft(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreIdent) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ACKMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotMessageHeader) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotChunkMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotAckMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotAskMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CellLocalState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftLocalState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftTruncatedState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftApplyState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipMraft(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthMraft = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMraft   = fmt.Errorf("proto: integer overflow")
)
