// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: raftcmdpb.proto

package raftcmdpb

import (
	"fmt"
	"math"

	errorpb "github.com/deepfabric/elasticell/pkg/pb/errorpb"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"

	metapb "github.com/deepfabric/elasticell/pkg/pb/metapb"
	pdpb "github.com/deepfabric/elasticell/pkg/pb/pdpb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMDType int32

const (
	Invalid   CMDType = 0
	RaftError CMDType = 1
	Snap      CMDType = 2
	// common
	Ping CMDType = 100
	Del  CMDType = 101
	// kv
	Set      CMDType = 200
	Get      CMDType = 201
	MSet     CMDType = 202
	MGet     CMDType = 203
	Incrby   CMDType = 204
	Decrby   CMDType = 205
	GetSet   CMDType = 206
	Append   CMDType = 207
	Setnx    CMDType = 208
	StrLen   CMDType = 209
	Incr     CMDType = 210
	Decr     CMDType = 211
	SetRange CMDType = 212
	MSetNX   CMDType = 213
	// Hash
	HSet     CMDType = 300
	HGet     CMDType = 301
	HDel     CMDType = 302
	HExists  CMDType = 303
	HKeys    CMDType = 304
	HVals    CMDType = 305
	HGetAll  CMDType = 306
	HLen     CMDType = 307
	HMGet    CMDType = 308
	HMSet    CMDType = 309
	HSetNX   CMDType = 310
	HStrLen  CMDType = 311
	HIncrBy  CMDType = 312
	HScanGet CMDType = 313
	// lists
	LIndex    CMDType = 400
	LInsert   CMDType = 401
	LLEN      CMDType = 402
	LPop      CMDType = 403
	LPush     CMDType = 404
	LPushX    CMDType = 405
	LRange    CMDType = 406
	LRem      CMDType = 407
	LSet      CMDType = 408
	LTrim     CMDType = 409
	RPop      CMDType = 410
	RPopLPush CMDType = 411
	RPush     CMDType = 412
	RPushX    CMDType = 413
	// sets
	SAdd      CMDType = 500
	SCard     CMDType = 501
	SRem      CMDType = 502
	SMembers  CMDType = 503
	SIsMember CMDType = 504
	SPop      CMDType = 505
	// zsets
	ZAdd             CMDType = 600
	ZCard            CMDType = 601
	ZCount           CMDType = 602
	ZIncrBy          CMDType = 603
	ZLexCount        CMDType = 604
	ZRange           CMDType = 605
	ZRangeByLex      CMDType = 606
	ZRangeByScore    CMDType = 607
	ZRank            CMDType = 608
	ZRem             CMDType = 609
	ZRemRangeByLex   CMDType = 611
	ZRemRangeByRank  CMDType = 612
	ZRemRangeByScore CMDType = 613
	ZScore           CMDType = 614
	// lock
	Lock     CMDType = 700
	Unlock   CMDType = 701
	Lockable CMDType = 702
	// bitmap
	BMCreate   CMDType = 800
	BMAdd      CMDType = 801
	BMRemove   CMDType = 802
	BMClear    CMDType = 803
	BMContains CMDType = 804
	BMDel      CMDType = 805
	BMCount    CMDType = 806
	BMRange    CMDType = 807
)

var CMDType_name = map[int32]string{
	0:   "Invalid",
	1:   "RaftError",
	2:   "Snap",
	100: "Ping",
	101: "Del",
	200: "Set",
	201: "Get",
	202: "MSet",
	203: "MGet",
	204: "Incrby",
	205: "Decrby",
	206: "GetSet",
	207: "Append",
	208: "Setnx",
	209: "StrLen",
	210: "Incr",
	211: "Decr",
	212: "SetRange",
	213: "MSetNX",
	300: "HSet",
	301: "HGet",
	302: "HDel",
	303: "HExists",
	304: "HKeys",
	305: "HVals",
	306: "HGetAll",
	307: "HLen",
	308: "HMGet",
	309: "HMSet",
	310: "HSetNX",
	311: "HStrLen",
	312: "HIncrBy",
	313: "HScanGet",
	400: "LIndex",
	401: "LInsert",
	402: "LLEN",
	403: "LPop",
	404: "LPush",
	405: "LPushX",
	406: "LRange",
	407: "LRem",
	408: "LSet",
	409: "LTrim",
	410: "RPop",
	411: "RPopLPush",
	412: "RPush",
	413: "RPushX",
	500: "SAdd",
	501: "SCard",
	502: "SRem",
	503: "SMembers",
	504: "SIsMember",
	505: "SPop",
	600: "ZAdd",
	601: "ZCard",
	602: "ZCount",
	603: "ZIncrBy",
	604: "ZLexCount",
	605: "ZRange",
	606: "ZRangeByLex",
	607: "ZRangeByScore",
	608: "ZRank",
	609: "ZRem",
	611: "ZRemRangeByLex",
	612: "ZRemRangeByRank",
	613: "ZRemRangeByScore",
	614: "ZScore",
	700: "Lock",
	701: "Unlock",
	702: "Lockable",
	800: "BMCreate",
	801: "BMAdd",
	802: "BMRemove",
	803: "BMClear",
	804: "BMContains",
	805: "BMDel",
	806: "BMCount",
	807: "BMRange",
}

var CMDType_value = map[string]int32{
	"Invalid":          0,
	"RaftError":        1,
	"Snap":             2,
	"Ping":             100,
	"Del":              101,
	"Set":              200,
	"Get":              201,
	"MSet":             202,
	"MGet":             203,
	"Incrby":           204,
	"Decrby":           205,
	"GetSet":           206,
	"Append":           207,
	"Setnx":            208,
	"StrLen":           209,
	"Incr":             210,
	"Decr":             211,
	"SetRange":         212,
	"MSetNX":           213,
	"HSet":             300,
	"HGet":             301,
	"HDel":             302,
	"HExists":          303,
	"HKeys":            304,
	"HVals":            305,
	"HGetAll":          306,
	"HLen":             307,
	"HMGet":            308,
	"HMSet":            309,
	"HSetNX":           310,
	"HStrLen":          311,
	"HIncrBy":          312,
	"HScanGet":         313,
	"LIndex":           400,
	"LInsert":          401,
	"LLEN":             402,
	"LPop":             403,
	"LPush":            404,
	"LPushX":           405,
	"LRange":           406,
	"LRem":             407,
	"LSet":             408,
	"LTrim":            409,
	"RPop":             410,
	"RPopLPush":        411,
	"RPush":            412,
	"RPushX":           413,
	"SAdd":             500,
	"SCard":            501,
	"SRem":             502,
	"SMembers":         503,
	"SIsMember":        504,
	"SPop":             505,
	"ZAdd":             600,
	"ZCard":            601,
	"ZCount":           602,
	"ZIncrBy":          603,
	"ZLexCount":        604,
	"ZRange":           605,
	"ZRangeByLex":      606,
	"ZRangeByScore":    607,
	"ZRank":            608,
	"ZRem":             609,
	"ZRemRangeByLex":   611,
	"ZRemRangeByRank":  612,
	"ZRemRangeByScore": 613,
	"ZScore":           614,
	"Lock":             700,
	"Unlock":           701,
	"Lockable":         702,
	"BMCreate":         800,
	"BMAdd":            801,
	"BMRemove":         802,
	"BMClear":          803,
	"BMContains":       804,
	"BMDel":            805,
	"BMCount":          806,
	"BMRange":          807,
}

func (x CMDType) Enum() *CMDType { _ = "STUB: not implemented"; return nil }

func (x CMDType) String() string { _ = "STUB: not implemented"; return "" }

func (x *CMDType) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

func (CMDType) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type AdminCmdType int32

const (
	InvalidAdmin   AdminCmdType = 0
	ChangePeer     AdminCmdType = 1
	Split          AdminCmdType = 2
	RaftLogGC      AdminCmdType = 3
	TransferLeader AdminCmdType = 4
	ComputeHash    AdminCmdType = 5
	VerifyHash     AdminCmdType = 6
)

var AdminCmdType_name = map[int32]string{
	0: "InvalidAdmin",
	1: "ChangePeer",
	2: "Split",
	3: "RaftLogGC",
	4: "TransferLeader",
	5: "ComputeHash",
	6: "VerifyHash",
}

var AdminCmdType_value = map[string]int32{
	"InvalidAdmin":   0,
	"ChangePeer":     1,
	"Split":          2,
	"RaftLogGC":      3,
	"TransferLeader": 4,
	"ComputeHash":    5,
	"VerifyHash":     6,
}

func (x AdminCmdType) Enum() *AdminCmdType { _ = "STUB: not implemented"; return nil }

func (x AdminCmdType) String() string { _ = "STUB: not implemented"; return "" }

func (x *AdminCmdType) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

func (AdminCmdType) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type RaftRequestHeader struct {
	CellId uint64      `protobuf:"varint,1,opt,name=cellId" json:"cellId"`
	Peer   metapb.Peer `protobuf:"bytes,2,opt,name=peer" json:"peer"`
	// true for read linearizati
	ReadQuorum bool `protobuf:"varint,3,opt,name=readQuorum" json:"readQuorum"`
	// 16 bytes, to distinguish request.
	UUID                 []byte           `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	CellEpoch            metapb.CellEpoch `protobuf:"bytes,5,opt,name=cellEpoch" json:"cellEpoch"`
	Term                 uint64           `protobuf:"varint,6,opt,name=term" json:"term"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RaftRequestHeader) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftRequestHeader) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftRequestHeader) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftRequestHeader) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftRequestHeader) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftRequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftRequestHeader) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftRequestHeader) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftRequestHeader) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftRequestHeader proto.InternalMessageInfo

func (m *RaftRequestHeader) GetCellId() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *RaftRequestHeader) GetPeer() metapb.Peer {
	_ = "STUB: not implemented"
	return *new(metapb.Peer)
}

func (m *RaftRequestHeader) GetReadQuorum() bool { _ = "STUB: not implemented"; return false }

func (m *RaftRequestHeader) GetUUID() []byte { _ = "STUB: not implemented"; return nil }

func (m *RaftRequestHeader) GetCellEpoch() metapb.CellEpoch {
	_ = "STUB: not implemented"
	return *new(metapb.CellEpoch)
}

func (m *RaftRequestHeader) GetTerm() uint64 { _ = "STUB: not implemented"; return 0 }

type RaftResponseHeader struct {
	Error                errorpb.Error `protobuf:"bytes,1,opt,name=error" json:"error"`
	UUID                 []byte        `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	CurrentTerm          uint64        `protobuf:"varint,3,opt,name=currentTerm" json:"currentTerm"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RaftResponseHeader) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftResponseHeader) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftResponseHeader) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftResponseHeader) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftResponseHeader) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftResponseHeader) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftResponseHeader) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftResponseHeader) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftResponseHeader proto.InternalMessageInfo

func (m *RaftResponseHeader) GetError() errorpb.Error {
	_ = "STUB: not implemented"
	return *new(errorpb.Error)
}

func (m *RaftResponseHeader) GetUUID() []byte { _ = "STUB: not implemented"; return nil }

func (m *RaftResponseHeader) GetCurrentTerm() uint64 { _ = "STUB: not implemented"; return 0 }

// RaftCMDRequest we can't include both normal requests and administrator request
// at same time.
type RaftCMDRequest struct {
	Header               *RaftRequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Requests             []*Request         `protobuf:"bytes,2,rep,name=requests" json:"requests,omitempty"`
	AdminRequest         *AdminRequest      `protobuf:"bytes,3,opt,name=adminRequest" json:"adminRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RaftCMDRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftCMDRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftCMDRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftCMDRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftCMDRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftCMDRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftCMDRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftCMDRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftCMDRequest proto.InternalMessageInfo

func (m *RaftCMDRequest) GetHeader() *RaftRequestHeader { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDRequest) GetRequests() []*Request { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDRequest) GetAdminRequest() *AdminRequest { _ = "STUB: not implemented"; return nil }

type RaftCMDResponse struct {
	Header               *RaftResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Responses            []*Response         `protobuf:"bytes,2,rep,name=responses" json:"responses,omitempty"`
	AdminResponse        *AdminResponse      `protobuf:"bytes,3,opt,name=adminResponse" json:"adminResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RaftCMDResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftCMDResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftCMDResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftCMDResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftCMDResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftCMDResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftCMDResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftCMDResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftCMDResponse proto.InternalMessageInfo

func (m *RaftCMDResponse) GetHeader() *RaftResponseHeader { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDResponse) GetResponses() []*Response { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDResponse) GetAdminResponse() *AdminResponse { _ = "STUB: not implemented"; return nil }

// admin request
type AdminRequest struct {
	Type                 AdminCmdType `protobuf:"varint,1,opt,name=type,enum=raftcmdpb.AdminCmdType" json:"type"`
	Body                 []byte       `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdminRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *AdminRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*AdminRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AdminRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AdminRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AdminRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AdminRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AdminRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AdminRequest proto.InternalMessageInfo

func (m *AdminRequest) GetType() AdminCmdType { _ = "STUB: not implemented"; return *new(AdminCmdType) }

func (m *AdminRequest) GetBody() []byte { _ = "STUB: not implemented"; return nil }

type AdminResponse struct {
	Type                 AdminCmdType `protobuf:"varint,1,opt,name=type,enum=raftcmdpb.AdminCmdType" json:"type"`
	Body                 []byte       `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdminResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *AdminResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*AdminResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AdminResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AdminResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AdminResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AdminResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AdminResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AdminResponse proto.InternalMessageInfo

func (m *AdminResponse) GetType() AdminCmdType {
	_ = "STUB: not implemented"
	return *new(AdminCmdType)
}

func (m *AdminResponse) GetBody() []byte { _ = "STUB: not implemented"; return nil }

type ChangePeerRequest struct {
	ChangeType           pdpb.ConfChangeType `protobuf:"varint,1,opt,name=changeType,enum=pdpb.ConfChangeType" json:"changeType"`
	Peer                 metapb.Peer         `protobuf:"bytes,2,opt,name=peer" json:"peer"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ChangePeerRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ChangePeerRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*ChangePeerRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ChangePeerRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ChangePeerRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ChangePeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ChangePeerRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ChangePeerRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ChangePeerRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ChangePeerRequest proto.InternalMessageInfo

func (m *ChangePeerRequest) GetChangeType() pdpb.ConfChangeType {
	_ = "STUB: not implemented"
	return *new(pdpb.ConfChangeType)
}

func (m *ChangePeerRequest) GetPeer() metapb.Peer {
	_ = "STUB: not implemented"
	return *new(metapb.Peer)
}

type ChangePeerResponse struct {
	Cell                 metapb.Cell `protobuf:"bytes,1,opt,name=cell" json:"cell"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChangePeerResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ChangePeerResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*ChangePeerResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ChangePeerResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ChangePeerResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ChangePeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ChangePeerResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ChangePeerResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ChangePeerResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ChangePeerResponse proto.InternalMessageInfo

func (m *ChangePeerResponse) GetCell() metapb.Cell {
	_ = "STUB: not implemented"
	return *new(metapb.Cell)
}

type SplitRequest struct {
	// This can be only called in internal RaftStore now.
	// The splitKey must be in the been splitting cell.
	SplitKey []byte `protobuf:"bytes,1,opt,name=splitKey" json:"splitKey,omitempty"`
	// We split the cell into two, first uses the origin
	// parent cell id, and the second uses the new_cell_id.
	// We must guarantee that the new_cell_id is global unique.
	NewCellID uint64 `protobuf:"varint,2,opt,name=newCellID" json:"newCellID"`
	// The peer ids for the new split cell.
	NewPeerIDs []uint64 `protobuf:"varint,3,rep,name=newPeerIDs" json:"newPeerIDs,omitempty"`
	// If true, right cell derive the origin cell_id,
	// left cell use new_cell_id.
	RightDerive          bool     `protobuf:"varint,4,opt,name=rightDerive" json:"rightDerive"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SplitRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*SplitRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SplitRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SplitRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SplitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SplitRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SplitRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SplitRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SplitRequest proto.InternalMessageInfo

func (m *SplitRequest) GetSplitKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *SplitRequest) GetNewCellID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *SplitRequest) GetNewPeerIDs() []uint64 { _ = "STUB: not implemented"; return nil }

func (m *SplitRequest) GetRightDerive() bool { _ = "STUB: not implemented"; return false }

type SplitResponse struct {
	Left                 metapb.Cell `protobuf:"bytes,1,opt,name=left" json:"left"`
	Right                metapb.Cell `protobuf:"bytes,2,opt,name=right" json:"right"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SplitResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SplitResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*SplitResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SplitResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SplitResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SplitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SplitResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SplitResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SplitResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SplitResponse proto.InternalMessageInfo

func (m *SplitResponse) GetLeft() metapb.Cell { _ = "STUB: not implemented"; return *new(metapb.Cell) }

func (m *SplitResponse) GetRight() metapb.Cell { _ = "STUB: not implemented"; return *new(metapb.Cell) }

type TransferLeaderRequest struct {
	Peer                 metapb.Peer `protobuf:"bytes,1,opt,name=peer" json:"peer"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransferLeaderRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *TransferLeaderRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*TransferLeaderRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*TransferLeaderRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferLeaderRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *TransferLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferLeaderRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TransferLeaderRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TransferLeaderRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TransferLeaderRequest proto.InternalMessageInfo

func (m *TransferLeaderRequest) GetPeer() metapb.Peer {
	_ = "STUB: not implemented"
	return *new(metapb.Peer)
}

type TransferLeaderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferLeaderResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *TransferLeaderResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*TransferLeaderResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*TransferLeaderResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferLeaderResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *TransferLeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferLeaderResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TransferLeaderResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TransferLeaderResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TransferLeaderResponse proto.InternalMessageInfo

type RaftLogGCRequest struct {
	CompactIndex         uint64   `protobuf:"varint,1,opt,name=compactIndex" json:"compactIndex"`
	CompactTerm          uint64   `protobuf:"varint,2,opt,name=compactTerm" json:"compactTerm"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftLogGCRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftLogGCRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftLogGCRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftLogGCRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftLogGCRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftLogGCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftLogGCRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftLogGCRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftLogGCRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftLogGCRequest proto.InternalMessageInfo

func (m *RaftLogGCRequest) GetCompactIndex() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *RaftLogGCRequest) GetCompactTerm() uint64 { _ = "STUB: not implemented"; return 0 }

type RaftLogGCResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftLogGCResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftLogGCResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftLogGCResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftLogGCResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftLogGCResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftLogGCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftLogGCResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftLogGCResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftLogGCResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftLogGCResponse proto.InternalMessageInfo

type FVPair struct {
	Field                []byte   `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FVPair) Reset()                    { _ = "STUB: not implemented"; return }
func (m *FVPair) String() string            { _ = "STUB: not implemented"; return "" }
func (*FVPair) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*FVPair) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *FVPair) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *FVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *FVPair) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *FVPair) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *FVPair) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_FVPair proto.InternalMessageInfo

func (m *FVPair) GetField() []byte { _ = "STUB: not implemented"; return nil }

func (m *FVPair) GetValue() []byte { _ = "STUB: not implemented"; return nil }

type ScorePair struct {
	Score                float64  `protobuf:"fixed64,1,opt,name=score" json:"score"`
	Member               []byte   `protobuf:"bytes,2,opt,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScorePair) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ScorePair) String() string            { _ = "STUB: not implemented"; return "" }
func (*ScorePair) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ScorePair) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ScorePair) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ScorePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ScorePair) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ScorePair) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ScorePair) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ScorePair proto.InternalMessageInfo

func (m *ScorePair) GetScore() float64 { _ = "STUB: not implemented"; return 0 }

func (m *ScorePair) GetMember() []byte { _ = "STUB: not implemented"; return nil }

type Request struct {
	UUID                 []byte   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Type                 CMDType  `protobuf:"varint,2,opt,name=type,enum=raftcmdpb.CMDType" json:"type"`
	Cmd                  [][]byte `protobuf:"bytes,3,rep,name=cmd" json:"cmd,omitempty"`
	Epoch                uint64   `protobuf:"varint,4,opt,name=epoch" json:"epoch"`
	StartAt              int64    `protobuf:"varint,5,opt,name=startAt" json:"startAt"`
	LastStageAt          int64    `protobuf:"varint,6,opt,name=lastStageAt" json:"lastStageAt"`
	SessionID            int64    `protobuf:"varint,7,opt,name=sessionID" json:"sessionID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Request) String() string            { _ = "STUB: not implemented"; return "" }
func (*Request) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Request) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Request) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Request) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Request) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Request) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUUID() []byte { _ = "STUB: not implemented"; return nil }

func (m *Request) GetType() CMDType { _ = "STUB: not implemented"; return *new(CMDType) }

func (m *Request) GetCmd() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *Request) GetEpoch() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Request) GetStartAt() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Request) GetLastStageAt() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Request) GetSessionID() int64 { _ = "STUB: not implemented"; return 0 }

type Response struct {
	UUID                         []byte        `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Type                         CMDType       `protobuf:"varint,2,opt,name=type,enum=raftcmdpb.CMDType" json:"type"`
	ErrorResult                  []byte        `protobuf:"bytes,3,opt,name=errorResult" json:"errorResult,omitempty"`
	ErrorResults                 [][]byte      `protobuf:"bytes,4,rep,name=errorResults" json:"errorResults,omitempty"`
	StatusResult                 []byte        `protobuf:"bytes,5,opt,name=statusResult" json:"statusResult,omitempty"`
	IntegerResult                *int64        `protobuf:"varint,6,opt,name=integerResult" json:"integerResult,omitempty"`
	BulkResult                   []byte        `protobuf:"bytes,7,opt,name=bulkResult" json:"bulkResult,omitempty"`
	HasEmptyBulkResult           bool          `protobuf:"varint,8,opt,name=hasEmptyBulkResult" json:"hasEmptyBulkResult"`
	SliceArrayResult             [][]byte      `protobuf:"bytes,9,rep,name=sliceArrayResult" json:"sliceArrayResult,omitempty"`
	HasEmptySliceArrayResult     bool          `protobuf:"varint,10,opt,name=hasEmptySliceArrayResult" json:"hasEmptySliceArrayResult"`
	FvPairArrayResult            []*FVPair     `protobuf:"bytes,11,rep,name=fvPairArrayResult" json:"fvPairArrayResult,omitempty"`
	HasEmptyFVPairArrayResult    bool          `protobuf:"varint,12,opt,name=hasEmptyFVPairArrayResult" json:"hasEmptyFVPairArrayResult"`
	ScorePairArrayResult         []*ScorePair  `protobuf:"bytes,13,rep,name=scorePairArrayResult" json:"scorePairArrayResult,omitempty"`
	HasEmptyScorePairArrayResult bool          `protobuf:"varint,14,opt,name=hasEmptyScorePairArrayResult" json:"hasEmptyScorePairArrayResult"`
	Withscores                   bool          `protobuf:"varint,15,opt,name=withscores" json:"withscores"`
	OriginRequest                *Request      `protobuf:"bytes,16,opt,name=originRequest" json:"originRequest,omitempty"`
	SessionID                    int64         `protobuf:"varint,17,opt,name=sessionID" json:"sessionID"`
	HasEmptyDocArrayResult       bool          `protobuf:"varint,18,opt,name=hasEmptyDocArrayResult" json:"hasEmptyDocArrayResult"`
	Error                        errorpb.Error `protobuf:"bytes,19,opt,name=error" json:"error"`
	XXX_NoUnkeyedLiteral         struct{}      `json:"-"`
	XXX_unrecognized             []byte        `json:"-"`
	XXX_sizecache                int32         `json:"-"`
}

func (m *Response) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Response) String() string            { _ = "STUB: not implemented"; return "" }
func (*Response) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Response) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Response) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Response) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Response) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Response) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUUID() []byte { _ = "STUB: not implemented"; return nil }

func (m *Response) GetType() CMDType { _ = "STUB: not implemented"; return *new(CMDType) }

func (m *Response) GetErrorResult() []byte { _ = "STUB: not implemented"; return nil }

func (m *Response) GetErrorResults() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *Response) GetStatusResult() []byte { _ = "STUB: not implemented"; return nil }

func (m *Response) GetIntegerResult() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Response) GetBulkResult() []byte { _ = "STUB: not implemented"; return nil }

func (m *Response) GetHasEmptyBulkResult() bool { _ = "STUB: not implemented"; return false }

func (m *Response) GetSliceArrayResult() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *Response) GetHasEmptySliceArrayResult() bool { _ = "STUB: not implemented"; return false }

func (m *Response) GetFvPairArrayResult() []*FVPair { _ = "STUB: not implemented"; return nil }

func (m *Response) GetHasEmptyFVPairArrayResult() bool { _ = "STUB: not implemented"; return false }

func (m *Response) GetScorePairArrayResult() []*ScorePair { _ = "STUB: not implemented"; return nil }

func (m *Response) GetHasEmptyScorePairArrayResult() bool { _ = "STUB: not implemented"; return false }

func (m *Response) GetWithscores() bool { _ = "STUB: not implemented"; return false }

func (m *Response) GetOriginRequest() *Request { _ = "STUB: not implemented"; return nil }

func (m *Response) GetSessionID() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Response) GetHasEmptyDocArrayResult() bool { _ = "STUB: not implemented"; return false }

func (m *Response) GetError() errorpb.Error { _ = "STUB: not implemented"; return *new(errorpb.Error) }

func init() {
	proto.RegisterEnum("raftcmdpb.CMDType", CMDType_name, CMDType_value)
	proto.RegisterEnum("raftcmdpb.AdminCmdType", AdminCmdType_name, AdminCmdType_value)
	proto.RegisterType((*RaftRequestHeader)(nil), "raftcmdpb.RaftRequestHeader")
	proto.RegisterType((*RaftResponseHeader)(nil), "raftcmdpb.RaftResponseHeader")
	proto.RegisterType((*RaftCMDRequest)(nil), "raftcmdpb.RaftCMDRequest")
	proto.RegisterType((*RaftCMDResponse)(nil), "raftcmdpb.RaftCMDResponse")
	proto.RegisterType((*AdminRequest)(nil), "raftcmdpb.AdminRequest")
	proto.RegisterType((*AdminResponse)(nil), "raftcmdpb.AdminResponse")
	proto.RegisterType((*ChangePeerRequest)(nil), "raftcmdpb.ChangePeerRequest")
	proto.RegisterType((*ChangePeerResponse)(nil), "raftcmdpb.ChangePeerResponse")
	proto.RegisterType((*SplitRequest)(nil), "raftcmdpb.SplitRequest")
	proto.RegisterType((*SplitResponse)(nil), "raftcmdpb.SplitResponse")
	proto.RegisterType((*TransferLeaderRequest)(nil), "raftcmdpb.TransferLeaderRequest")
	proto.RegisterType((*TransferLeaderResponse)(nil), "raftcmdpb.TransferLeaderResponse")
	proto.RegisterType((*RaftLogGCRequest)(nil), "raftcmdpb.RaftLogGCRequest")
	proto.RegisterType((*RaftLogGCResponse)(nil), "raftcmdpb.RaftLogGCResponse")
	proto.RegisterType((*FVPair)(nil), "raftcmdpb.FVPair")
	proto.RegisterType((*ScorePair)(nil), "raftcmdpb.ScorePair")
	proto.RegisterType((*Request)(nil), "raftcmdpb.Request")
	proto.RegisterType((*Response)(nil), "raftcmdpb.Response")
}

func init() { proto.RegisterFile("raftcmdpb.proto", fileDescriptor_c4d8ad5550754569) }

var fileDescriptor_c4d8ad5550754569 = []byte{
	// 1811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4b, 0x6c, 0x23, 0x59,
	0xd5, 0x4e, 0xd9, 0xe5, 0xd7, 0xb1, 0x9d, 0xdc, 0xdc, 0xa4, 0xfb, 0xf7, 0x1f, 0x35, 0x99, 0xc8,
	0x1a, 0xb5, 0xa2, 0x16, 0x4a, 0x8b, 0x56, 0x23, 0x24, 0x18, 0xd1, 0xc4, 0x76, 0x68, 0x5b, 0xe3,
	0x8c, 0x42, 0x39, 0xdd, 0x1a, 0x65, 0x57, 0x76, 0xdd, 0x38, 0xa5, 0x2e, 0x57, 0x15, 0x55, 0xe5,
	0x74, 0xbc, 0x62, 0x07, 0x5b, 0x9e, 0xc3, 0xf0, 0x92, 0x78, 0xb3, 0xe1, 0xfd, 0x1a, 0x90, 0x80,
	0x1d, 0x52, 0xf3, 0x18, 0x68, 0x5e, 0x12, 0xcf, 0x66, 0xa6, 0x07, 0x58, 0xc2, 0x86, 0xe7, 0x0e,
	0x9d, 0x73, 0x6f, 0xd9, 0xd7, 0x49, 0x7a, 0x86, 0xc5, 0xac, 0x7c, 0xce, 0x77, 0xde, 0xa7, 0xee,
	0x39, 0xf7, 0x1a, 0x96, 0x22, 0xfb, 0x30, 0x19, 0x8c, 0x9c, 0xb0, 0xbf, 0x15, 0x46, 0x41, 0x12,
	0xf0, 0xd2, 0x14, 0x58, 0x5b, 0x19, 0x89, 0xc4, 0x0e, 0xfb, 0x57, 0xe5, 0x8f, 0x94, 0xaf, 0x2d,
	0x85, 0x4e, 0xd8, 0xbf, 0x1a, 0x4e, 0x0d, 0xd6, 0x2e, 0x88, 0x28, 0x0a, 0xa2, 0xb0, 0x7f, 0x55,
	0xfd, 0x2a, 0x78, 0x75, 0x18, 0x0c, 0x03, 0x22, 0xaf, 0x22, 0x25, 0xd1, 0xfa, 0x5f, 0x0d, 0x58,
	0xb6, 0xec, 0xc3, 0xc4, 0x12, 0x6f, 0x1f, 0x8b, 0x38, 0x69, 0x0b, 0xdb, 0x11, 0x11, 0xbf, 0x04,
	0xf9, 0x81, 0xf0, 0xbc, 0x8e, 0x53, 0x33, 0x36, 0x8c, 0x4d, 0xb3, 0x61, 0xde, 0x7b, 0xf0, 0xd8,
	0x82, 0xa5, 0x30, 0x7e, 0x19, 0xcc, 0x50, 0x88, 0xa8, 0x96, 0xd9, 0x30, 0x36, 0xcb, 0xd7, 0x2a,
	0x5b, 0x2a, 0x9d, 0x3d, 0x21, 0x22, 0xa5, 0x49, 0x72, 0xfe, 0x38, 0x40, 0x24, 0x6c, 0xe7, 0x6d,
	0xe3, 0x20, 0x1a, 0x8f, 0x6a, 0xd9, 0x0d, 0x63, 0xb3, 0xa8, 0xe4, 0x1a, 0xce, 0x2f, 0x81, 0x39,
	0x1e, 0xbb, 0x4e, 0xcd, 0xdc, 0x30, 0x36, 0x2b, 0x8d, 0xe2, 0xc3, 0x07, 0x8f, 0x99, 0xb7, 0x6e,
	0x75, 0x5a, 0x16, 0xa1, 0xfc, 0xf5, 0x50, 0xc2, 0xa8, 0x3b, 0x61, 0x30, 0x38, 0xaa, 0xe5, 0x28,
	0xe0, 0x72, 0x1a, 0xb0, 0x99, 0x0a, 0x94, 0xd7, 0x99, 0x26, 0xaf, 0x81, 0x99, 0x88, 0x68, 0x54,
	0xcb, 0x6b, 0xe9, 0x13, 0x52, 0x7f, 0xa7, 0x01, 0x5c, 0x16, 0x1c, 0x87, 0x81, 0x1f, 0x0b, 0x55,
	0xf1, 0x15, 0xc8, 0x51, 0xbb, 0xa8, 0xe0, 0xf2, 0xb5, 0xc5, 0xad, 0xb4, 0x79, 0x3b, 0xf8, 0xab,
	0x3c, 0x48, 0x95, 0x69, 0xc6, 0x99, 0x73, 0x33, 0xbe, 0x0c, 0xe5, 0xc1, 0x38, 0x8a, 0x84, 0x9f,
	0xec, 0x63, 0x06, 0x59, 0x2d, 0x03, 0x5d, 0x50, 0xff, 0xbe, 0x01, 0x8b, 0x98, 0x48, 0x73, 0xb7,
	0xa5, 0x9a, 0xcf, 0xdf, 0x08, 0xf9, 0x23, 0x4a, 0x47, 0x65, 0x71, 0x69, 0x6b, 0x76, 0x18, 0xce,
	0x7c, 0x24, 0xf2, 0x69, 0x58, 0xca, 0x82, 0x5f, 0x87, 0x62, 0x24, 0xc5, 0x71, 0x2d, 0xb3, 0x91,
	0xdd, 0x2c, 0x5f, 0xe3, 0xba, 0xb5, 0x14, 0x29, 0x9b, 0xa9, 0x26, 0xdf, 0x86, 0x8a, 0xed, 0x8c,
	0x5c, 0x5f, 0xc9, 0x29, 0xdb, 0xf2, 0xb5, 0xff, 0xd3, 0x2c, 0xb7, 0x35, 0xb1, 0x32, 0x9f, 0x33,
	0xa9, 0x3f, 0x6f, 0xc0, 0xd2, 0xb4, 0x0e, 0xd9, 0x53, 0xfe, 0xa6, 0x53, 0x85, 0xbc, 0xe6, 0x4c,
	0x21, 0x7a, 0xf3, 0x4f, 0x55, 0xf2, 0x06, 0x28, 0x45, 0x4a, 0x9e, 0x96, 0xb2, 0x32, 0x57, 0x8a,
	0x94, 0x29, 0xab, 0x99, 0x2e, 0x6f, 0x41, 0x55, 0x65, 0x26, 0x11, 0x55, 0x4d, 0xed, 0x6c, 0x35,
	0x73, 0x1e, 0xe6, 0x8d, 0xea, 0xb7, 0xa0, 0xa2, 0xd7, 0xcc, 0x5f, 0x07, 0x66, 0x32, 0x09, 0x05,
	0x55, 0xb2, 0x78, 0xb6, 0x35, 0xcd, 0x91, 0xb3, 0x3f, 0x09, 0xc5, 0xf4, 0x8c, 0x4d, 0x42, 0xc1,
	0x39, 0x98, 0xfd, 0xc0, 0x99, 0xc8, 0x03, 0x62, 0x11, 0x5d, 0xbf, 0x0d, 0xd5, 0xb9, 0xe0, 0xaf,
	0x96, 0xdf, 0xbb, 0xb0, 0xdc, 0x3c, 0xb2, 0xfd, 0xa1, 0xc0, 0xf1, 0x9b, 0x1d, 0x24, 0x18, 0x10,
	0xb8, 0x3f, 0x8b, 0xb0, 0xba, 0x45, 0x3b, 0xa2, 0x19, 0xf8, 0x87, 0xcd, 0xa9, 0x2c, 0x9d, 0xc7,
	0x99, 0xf6, 0xff, 0x3a, 0xdd, 0xf5, 0x27, 0x80, 0xeb, 0x81, 0x55, 0x55, 0x97, 0xc1, 0xc4, 0x29,
	0x54, 0xdf, 0xbd, 0xa2, 0x8f, 0x6a, 0x6a, 0x8d, 0xf2, 0xfa, 0x33, 0x06, 0x54, 0x7a, 0xa1, 0xe7,
	0xa6, 0x67, 0x9a, 0xaf, 0x41, 0x31, 0x46, 0xfe, 0x49, 0x31, 0x21, 0xe3, 0x8a, 0x35, 0xe5, 0x79,
	0x1d, 0x4a, 0xbe, 0xb8, 0x8b, 0x3e, 0x3a, 0x2d, 0xca, 0x2b, 0x1d, 0xa8, 0x19, 0xcc, 0xd7, 0x01,
	0x7c, 0x71, 0x17, 0x73, 0xe9, 0xb4, 0xe2, 0x5a, 0x76, 0x23, 0xbb, 0x69, 0x5a, 0x1a, 0x82, 0x63,
	0x19, 0xb9, 0xc3, 0xa3, 0xa4, 0x25, 0x22, 0xf7, 0x58, 0xd0, 0xb6, 0x49, 0xb7, 0x91, 0x2e, 0xa8,
	0xdb, 0x50, 0x55, 0x79, 0xcd, 0x2a, 0xf2, 0xc4, 0x61, 0xf2, 0x72, 0x15, 0xa1, 0x9c, 0x6f, 0x42,
	0x8e, 0xfc, 0x9c, 0x6e, 0x9c, 0xa6, 0x28, 0x15, 0xea, 0x37, 0xe0, 0xc2, 0x7e, 0x64, 0xfb, 0xf1,
	0xa1, 0x88, 0xba, 0x74, 0xe4, 0xd3, 0x1e, 0xa4, 0xad, 0x37, 0x5e, 0xa1, 0xf5, 0x35, 0xb8, 0x78,
	0xda, 0x81, 0x3a, 0xbc, 0x0e, 0x30, 0x9c, 0xaf, 0x6e, 0x30, 0xbc, 0xd9, 0x4c, 0xbd, 0x6e, 0x42,
	0x65, 0x10, 0x8c, 0x42, 0x7b, 0x90, 0x74, 0x7c, 0x47, 0x9c, 0xcc, 0xad, 0xf4, 0x39, 0x09, 0xad,
	0x2e, 0xc9, 0xd3, 0xea, 0xca, 0xcc, 0xad, 0xae, 0x99, 0xa0, 0xbe, 0x22, 0xef, 0x0c, 0x15, 0x45,
	0x85, 0xbe, 0x0e, 0xf9, 0xb7, 0xde, 0xde, 0xb3, 0xdd, 0x88, 0xaf, 0x42, 0xee, 0xd0, 0x15, 0x9e,
	0xa3, 0xbe, 0xa3, 0x64, 0x10, 0x3d, 0xb6, 0xbd, 0xb1, 0x50, 0xa7, 0x57, 0x32, 0xf5, 0x1b, 0x50,
	0xea, 0x0d, 0x82, 0x48, 0x90, 0xe1, 0x1a, 0xe4, 0x62, 0x64, 0xc8, 0xd0, 0x48, 0x9b, 0x46, 0x10,
	0xbf, 0x08, 0xf9, 0x91, 0x18, 0xf5, 0xd5, 0xc1, 0xac, 0x58, 0x8a, 0xab, 0xff, 0xcd, 0x80, 0x42,
	0x5a, 0x69, 0xba, 0x98, 0x8d, 0x73, 0x17, 0xf3, 0x6b, 0xd5, 0xc0, 0x65, 0x68, 0x1c, 0xf4, 0xed,
	0xd8, 0xdc, 0x6d, 0x9d, 0x99, 0x35, 0x06, 0xd9, 0xc1, 0xc8, 0xa1, 0x83, 0x54, 0xb1, 0x90, 0xc4,
	0xec, 0x04, 0x5d, 0x43, 0xa6, 0xd6, 0x17, 0x09, 0xf1, 0x75, 0x28, 0xc4, 0x89, 0x1d, 0x25, 0xdb,
	0x09, 0x5d, 0x52, 0x59, 0x25, 0x4d, 0x41, 0xec, 0xac, 0x67, 0xc7, 0x49, 0x2f, 0xb1, 0x87, 0x62,
	0x3b, 0xa1, 0x6b, 0x29, 0xd5, 0xd1, 0x05, 0x78, 0xd2, 0x63, 0x11, 0xc7, 0x6e, 0xe0, 0x77, 0x5a,
	0xb5, 0x82, 0xa6, 0x35, 0x83, 0xeb, 0xcf, 0x15, 0xa0, 0x38, 0x3d, 0x9d, 0xaf, 0x66, 0xc9, 0x1b,
	0x50, 0xa6, 0x0b, 0xce, 0x12, 0xf1, 0xd8, 0x93, 0x77, 0x41, 0xc5, 0xd2, 0x21, 0x5e, 0x87, 0x8a,
	0xc6, 0xc6, 0x35, 0x93, 0xba, 0x33, 0x87, 0xa1, 0x4e, 0x9c, 0xd8, 0xc9, 0x38, 0x56, 0x6e, 0x72,
	0xe4, 0x66, 0x0e, 0xe3, 0x8f, 0x43, 0xd5, 0xf5, 0x13, 0x31, 0x14, 0x69, 0x2c, 0x6a, 0x88, 0x35,
	0x0f, 0xe2, 0x48, 0xf7, 0xc7, 0xde, 0x1d, 0xa5, 0x52, 0x20, 0x3f, 0x1a, 0xc2, 0xaf, 0x03, 0x3f,
	0xb2, 0xe3, 0x9d, 0x51, 0x98, 0x4c, 0x1a, 0x33, 0xbd, 0xa2, 0x36, 0xd9, 0xe7, 0xc8, 0xf9, 0x15,
	0x60, 0xb1, 0xe7, 0x0e, 0xc4, 0x76, 0x14, 0xd9, 0x13, 0x65, 0x53, 0xa2, 0x3a, 0xce, 0xe0, 0xfc,
	0x2d, 0x50, 0x4b, 0x3d, 0xf4, 0x4e, 0xdb, 0x80, 0x16, 0xe7, 0x91, 0x5a, 0xfc, 0x06, 0x2c, 0x1f,
	0x1e, 0xe3, 0xe1, 0xd6, 0x4d, 0xcb, 0x74, 0xa9, 0x2d, 0x6b, 0x9f, 0x43, 0x4e, 0x8e, 0x75, 0x56,
	0x97, 0x37, 0xe0, 0xff, 0x53, 0xe7, 0x52, 0x49, 0x77, 0x54, 0xd1, 0x72, 0x78, 0xb4, 0x1a, 0x6f,
	0xc3, 0x6a, 0x9c, 0x0e, 0x99, 0x6e, 0x5e, 0xa5, 0x3c, 0x56, 0xb5, 0x3c, 0xa6, 0xb3, 0x68, 0x9d,
	0x6b, 0xc1, 0xdb, 0x70, 0x69, 0x5a, 0xea, 0x79, 0x1e, 0x17, 0xb5, 0x84, 0x5e, 0x56, 0x13, 0x1f,
	0x87, 0x77, 0xdd, 0xe4, 0x88, 0xa2, 0xc4, 0xb5, 0x25, 0xfd, 0x71, 0x38, 0xc3, 0xf9, 0x9b, 0xa1,
	0x1a, 0x44, 0xee, 0x70, 0xf6, 0x40, 0x61, 0xb4, 0x1a, 0x1f, 0xfd, 0xb4, 0x99, 0x57, 0x9f, 0x9f,
	0xa7, 0xe5, 0x73, 0xe7, 0x89, 0x3f, 0x01, 0x17, 0xd3, 0x4c, 0x5b, 0xc1, 0x40, 0xaf, 0x86, 0x6b,
	0x59, 0x3d, 0x42, 0x67, 0xf6, 0x70, 0x5c, 0x79, 0xc5, 0x87, 0xe3, 0x95, 0x77, 0x15, 0xa1, 0xa0,
	0x06, 0x8f, 0x97, 0xa1, 0xd0, 0xf1, 0x8f, 0x6d, 0xcf, 0x75, 0xd8, 0x02, 0xaf, 0x42, 0x09, 0x17,
	0x2a, 0x99, 0x30, 0x83, 0x17, 0xc1, 0xec, 0xf9, 0x76, 0xc8, 0x32, 0x48, 0xed, 0xb9, 0xfe, 0x90,
	0x39, 0xbc, 0x00, 0xd9, 0x96, 0xf0, 0x98, 0xe0, 0x45, 0xc8, 0xf6, 0x44, 0xc2, 0xee, 0xa1, 0x5a,
	0xf6, 0xa6, 0x48, 0xd8, 0x0f, 0x0c, 0x5e, 0x02, 0x73, 0x17, 0xc1, 0x1f, 0x4a, 0x12, 0xd1, 0x1f,
	0x19, 0xbc, 0x0c, 0xf9, 0x8e, 0x3f, 0x88, 0xfa, 0x13, 0xf6, 0x63, 0x62, 0x5a, 0x82, 0x98, 0xe7,
	0x89, 0xb9, 0x29, 0x12, 0xb4, 0xf8, 0x09, 0x31, 0xdb, 0x61, 0x28, 0x7c, 0x87, 0xfd, 0xd4, 0xe0,
	0x00, 0xb9, 0x9e, 0x48, 0xfc, 0x13, 0x76, 0x9f, 0x04, 0xbd, 0x24, 0xea, 0x0a, 0x9f, 0xfd, 0x8c,
	0xfc, 0xa2, 0x33, 0xf6, 0x73, 0x22, 0xd1, 0x15, 0xfb, 0x85, 0xc1, 0xab, 0x50, 0xec, 0x89, 0xc4,
	0xc2, 0x67, 0x00, 0xfb, 0x25, 0x59, 0x60, 0x1e, 0x4f, 0x3d, 0xcd, 0x7e, 0x45, 0x6a, 0x6d, 0x0c,
	0xf1, 0xf9, 0x0c, 0x91, 0x98, 0xd4, 0x17, 0x24, 0x89, 0x85, 0x7c, 0x31, 0xc3, 0x2b, 0x50, 0x68,
	0xef, 0x9c, 0xb8, 0x71, 0x12, 0xb3, 0x2f, 0x65, 0x30, 0x72, 0xfb, 0x49, 0x31, 0x89, 0xd9, 0x97,
	0x25, 0x7d, 0xdb, 0xf6, 0x62, 0xf6, 0x15, 0xa9, 0x75, 0x53, 0x24, 0xdb, 0x9e, 0xc7, 0xbe, 0x2a,
	0xcd, 0x31, 0xa3, 0xaf, 0x49, 0x25, 0x2a, 0xf5, 0xeb, 0x8a, 0xc6, 0x60, 0xdf, 0xc8, 0x60, 0x12,
	0x6d, 0x99, 0xc4, 0x37, 0xa5, 0xb5, 0x2a, 0xe2, 0x39, 0xc9, 0x61, 0x15, 0x8d, 0x09, 0xfb, 0x56,
	0x06, 0x93, 0x6f, 0xf7, 0x06, 0xb6, 0x8f, 0x3e, 0xbe, 0x4d, 0x76, 0x5d, 0xba, 0x07, 0xd9, 0xbb,
	0xb3, 0xa8, 0xd9, 0xed, 0xf8, 0xb1, 0x88, 0x12, 0xf6, 0x9e, 0x2c, 0x46, 0xed, 0x76, 0x77, 0x9e,
	0x62, 0xef, 0x95, 0xe4, 0x5e, 0x10, 0xb2, 0xf7, 0x65, 0x31, 0x68, 0x77, 0x6f, 0x1c, 0x1f, 0xb1,
	0xf7, 0x67, 0xc9, 0x18, 0xe9, 0xa7, 0xd9, 0x07, 0x24, 0x23, 0x7b, 0xf2, 0x8c, 0x34, 0xb0, 0xc4,
	0x88, 0x7d, 0x50, 0x92, 0x98, 0xe4, 0xb3, 0xd2, 0x76, 0x3f, 0x72, 0x47, 0xec, 0x43, 0x04, 0x5b,
	0xe8, 0xf2, 0xc3, 0x59, 0xbe, 0x08, 0x25, 0x24, 0xa5, 0xdb, 0x8f, 0x90, 0x9a, 0x45, 0xf4, 0x47,
	0xc9, 0xab, 0x25, 0x43, 0x7c, 0x8c, 0x6c, 0x7a, 0xdb, 0x8e, 0xc3, 0xfe, 0x4e, 0x3a, 0xbd, 0xa6,
	0x1d, 0x39, 0xec, 0x1f, 0x12, 0xc6, 0x60, 0xff, 0xcc, 0xd2, 0xa7, 0xd9, 0xa5, 0x3b, 0x32, 0x66,
	0xff, 0x22, 0xcf, 0xbd, 0x4e, 0x2c, 0x01, 0xf6, 0x6f, 0xa9, 0x89, 0x41, 0xff, 0x43, 0xe4, 0x01,
	0xfa, 0xfa, 0xb5, 0x89, 0xbe, 0x0e, 0xc8, 0xd7, 0x6f, 0x4c, 0x8c, 0x77, 0xd0, 0x0c, 0xc6, 0x7e,
	0xc2, 0x7e, 0x6b, 0x62, 0x3f, 0x0e, 0x54, 0xe7, 0x7e, 0x67, 0xa2, 0xb3, 0x83, 0xae, 0x38, 0x91,
	0xd2, 0xdf, 0x4b, 0x55, 0x59, 0xf0, 0x1f, 0x4c, 0xce, 0xa0, 0x2c, 0x99, 0xc6, 0xa4, 0x2b, 0x4e,
	0xd8, 0x03, 0x93, 0x73, 0xa8, 0xa6, 0x08, 0xed, 0x02, 0xf6, 0x47, 0x19, 0xc9, 0xb2, 0xfd, 0x3b,
	0xec, 0x05, 0x93, 0x12, 0xc0, 0xac, 0x5f, 0x34, 0xf9, 0x0a, 0x2c, 0x22, 0xa9, 0xd9, 0xbf, 0x64,
	0xf2, 0x55, 0x58, 0xd2, 0x40, 0xb2, 0xfa, 0x93, 0xc9, 0x2f, 0x00, 0xd3, 0x50, 0xe9, 0xf8, 0xcf,
	0x32, 0x17, 0xc9, 0xfc, 0x85, 0x3c, 0x77, 0x83, 0xc1, 0x1d, 0xf6, 0x9d, 0x1c, 0xe2, 0xb7, 0x7c,
	0x0f, 0x99, 0xef, 0xe6, 0xb0, 0x39, 0x88, 0xdb, 0x7d, 0x4f, 0xb0, 0xef, 0x11, 0xdb, 0xd8, 0x6d,
	0x46, 0xc2, 0x4e, 0x04, 0xfb, 0x78, 0x1e, 0x73, 0x6b, 0xec, 0x62, 0x47, 0x3e, 0x91, 0x97, 0x22,
	0x4b, 0x8c, 0x82, 0x63, 0xc1, 0x3e, 0x99, 0xc7, 0x3e, 0x34, 0x76, 0x9b, 0x9e, 0xb0, 0x23, 0xf6,
	0xa9, 0x3c, 0x5f, 0x02, 0x68, 0xec, 0x36, 0x03, 0x3f, 0xb1, 0x5d, 0x3f, 0x66, 0x9f, 0x56, 0x96,
	0x78, 0xbc, 0x3f, 0x93, 0xaa, 0x52, 0x8b, 0x3e, 0xab, 0x38, 0xd9, 0xa3, 0xcf, 0xe5, 0xaf, 0xbc,
	0x43, 0xfd, 0xc9, 0x50, 0xaf, 0x7c, 0xce, 0xa0, 0xa2, 0xb6, 0x01, 0xc1, 0x6c, 0x81, 0x2f, 0x02,
	0xcc, 0x9e, 0xd7, 0x0c, 0xa7, 0x29, 0x47, 0xef, 0x52, 0x96, 0x49, 0xb7, 0x05, 0x3d, 0xbf, 0x58,
	0x96, 0x73, 0x58, 0x9c, 0x7f, 0x0d, 0x32, 0x93, 0x2f, 0x41, 0xb9, 0x19, 0x8c, 0xc2, 0x71, 0x22,
	0xda, 0x76, 0x7c, 0xc4, 0x72, 0xe8, 0xee, 0xb6, 0x88, 0xdc, 0xc3, 0x09, 0xf1, 0xf9, 0xc6, 0xea,
	0xfd, 0x17, 0xd7, 0x17, 0xee, 0x3d, 0x5c, 0x37, 0xee, 0x3f, 0x5c, 0x37, 0x5e, 0x78, 0xb8, 0x6e,
	0x3c, 0xfb, 0xd2, 0xfa, 0xc2, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xed, 0x34, 0x68, 0x5f, 0x7d,
	0x10, 0x00, 0x00,
}

func (m *RaftRequestHeader) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftRequestHeader) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftRequestHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftResponseHeader) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftResponseHeader) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftResponseHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftCMDRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftCMDRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftCMDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftCMDResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftCMDResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftCMDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AdminRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AdminRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AdminRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AdminResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AdminResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AdminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ChangePeerRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ChangePeerRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ChangePeerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ChangePeerResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ChangePeerResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ChangePeerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SplitRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SplitRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SplitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SplitResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SplitResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SplitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TransferLeaderRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferLeaderRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TransferLeaderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TransferLeaderResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferLeaderResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TransferLeaderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftLogGCRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftLogGCRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftLogGCRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftLogGCResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftLogGCResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftLogGCResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *FVPair) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *FVPair) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *FVPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ScorePair) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ScorePair) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ScorePair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Request) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Request) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Response) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Response) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintRaftcmdpb(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *RaftRequestHeader) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftResponseHeader) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftCMDRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftCMDResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AdminRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AdminResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ChangePeerRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ChangePeerResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SplitRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SplitResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TransferLeaderRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TransferLeaderResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftLogGCRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftLogGCResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *FVPair) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ScorePair) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Request) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Response) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovRaftcmdpb(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozRaftcmdpb(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftRequestHeader) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftResponseHeader) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftCMDResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AdminRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AdminResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ChangePeerRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ChangePeerResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SplitRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SplitResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TransferLeaderRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TransferLeaderResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RaftLogGCRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftLogGCResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *FVPair) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ScorePair) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Request) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Response) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipRaftcmdpb(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthRaftcmdpb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRaftcmdpb   = fmt.Errorf("proto: integer overflow")
)
