// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metapb.proto

package metapb

import (
	"fmt"
	"math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreState int32

const (
	UP        StoreState = 0
	Down      StoreState = 1
	Tombstone StoreState = 2
)

var StoreState_name = map[int32]string{
	0: "UP",
	1: "Down",
	2: "Tombstone",
}

var StoreState_value = map[string]int32{
	"UP":        0,
	"Down":      1,
	"Tombstone": 2,
}

func (x StoreState) Enum() *StoreState { _ = "STUB: not implemented"; return nil }

func (x StoreState) String() string { _ = "STUB: not implemented"; return "" }

func (x *StoreState) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

func (StoreState) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type Label struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Label) String() string            { _ = "STUB: not implemented"; return "" }
func (*Label) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Label) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Label) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Label) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Label) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Label) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetKey() string { _ = "STUB: not implemented"; return "" }

func (m *Label) GetValue() string { _ = "STUB: not implemented"; return "" }

type Cluster struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=id" json:"id"`
	MaxReplicas          uint32   `protobuf:"varint,2,opt,name=maxReplicas" json:"maxReplicas"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Cluster) String() string            { _ = "STUB: not implemented"; return "" }
func (*Cluster) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Cluster) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Cluster) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Cluster) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Cluster) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Cluster) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Cluster) GetMaxReplicas() uint32 { _ = "STUB: not implemented"; return 0 }

type Peer struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=id" json:"id"`
	StoreID              uint64   `protobuf:"varint,2,opt,name=storeID" json:"storeID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Peer) String() string            { _ = "STUB: not implemented"; return "" }
func (*Peer) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Peer) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Peer) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Peer) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Peer) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Peer) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Peer) GetStoreID() uint64 { _ = "STUB: not implemented"; return 0 }

type CellEpoch struct {
	ConfVer              uint64   `protobuf:"varint,1,opt,name=confVer" json:"confVer"`
	CellVer              uint64   `protobuf:"varint,2,opt,name=cellVer" json:"cellVer"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellEpoch) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CellEpoch) String() string            { _ = "STUB: not implemented"; return "" }
func (*CellEpoch) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CellEpoch) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CellEpoch) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CellEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CellEpoch) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CellEpoch) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CellEpoch) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CellEpoch proto.InternalMessageInfo

func (m *CellEpoch) GetConfVer() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *CellEpoch) GetCellVer() uint64 { _ = "STUB: not implemented"; return 0 }

type Cell struct {
	ID                   uint64    `protobuf:"varint,1,opt,name=id" json:"id"`
	Start                []byte    `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	End                  []byte    `protobuf:"bytes,3,opt,name=end" json:"end,omitempty"`
	Epoch                CellEpoch `protobuf:"bytes,4,opt,name=epoch" json:"epoch"`
	Peers                []*Peer   `protobuf:"bytes,5,rep,name=peers" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Cell) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Cell) String() string            { _ = "STUB: not implemented"; return "" }
func (*Cell) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Cell) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Cell) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Cell) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Cell) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Cell) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Cell proto.InternalMessageInfo

func (m *Cell) GetID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Cell) GetStart() []byte { _ = "STUB: not implemented"; return nil }

func (m *Cell) GetEnd() []byte { _ = "STUB: not implemented"; return nil }

func (m *Cell) GetEpoch() CellEpoch { _ = "STUB: not implemented"; return *new(CellEpoch) }

func (m *Cell) GetPeers() []*Peer { _ = "STUB: not implemented"; return nil }

type Store struct {
	ID                   uint64     `protobuf:"varint,1,opt,name=id" json:"id"`
	Address              string     `protobuf:"bytes,2,opt,name=address" json:"address"`
	Lables               []Label    `protobuf:"bytes,3,rep,name=lables" json:"lables"`
	State                StoreState `protobuf:"varint,4,opt,name=state,enum=metapb.StoreState" json:"state"`
	ClientAddress        string     `protobuf:"bytes,5,opt,name=clientAddress" json:"clientAddress"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Store) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Store) String() string            { _ = "STUB: not implemented"; return "" }
func (*Store) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Store) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Store) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Store) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Store) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Store) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Store) GetAddress() string { _ = "STUB: not implemented"; return "" }

func (m *Store) GetLables() []Label { _ = "STUB: not implemented"; return nil }

func (m *Store) GetState() StoreState { _ = "STUB: not implemented"; return *new(StoreState) }

func (m *Store) GetClientAddress() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterEnum("metapb.StoreState", StoreState_name, StoreState_value)
	proto.RegisterType((*Label)(nil), "metapb.Label")
	proto.RegisterType((*Cluster)(nil), "metapb.Cluster")
	proto.RegisterType((*Peer)(nil), "metapb.Peer")
	proto.RegisterType((*CellEpoch)(nil), "metapb.CellEpoch")
	proto.RegisterType((*Cell)(nil), "metapb.Cell")
	proto.RegisterType((*Store)(nil), "metapb.Store")
}

func init() { proto.RegisterFile("metapb.proto", fileDescriptor_77b4d575d5a68dda) }

var fileDescriptor_77b4d575d5a68dda = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0x24, 0xee, 0xe8, 0xdb, 0x16, 0x15, 0xab, 0x42, 0x51, 0x0f, 0x59, 0x95, 0x03,
	0xaa, 0x86, 0x56, 0xa4, 0x5e, 0x39, 0xd1, 0x95, 0xc3, 0x04, 0x48, 0x53, 0x06, 0xdc, 0x9d, 0xe4,
	0x65, 0x44, 0xb8, 0x71, 0x14, 0x7b, 0xfc, 0xf9, 0x26, 0xdc, 0xf9, 0x32, 0x3b, 0x70, 0xd8, 0x27,
	0x98, 0x20, 0x7c, 0x11, 0x64, 0xc7, 0x81, 0xf6, 0xb2, 0xde, 0xec, 0xe7, 0xf9, 0xe5, 0xf1, 0xf3,
	0xda, 0x81, 0xd1, 0x16, 0x35, 0xaf, 0xd2, 0x65, 0x55, 0x4b, 0x2d, 0x59, 0xbf, 0xdd, 0xcd, 0xa6,
	0x57, 0xf2, 0x4a, 0x5a, 0xe9, 0x99, 0x59, 0xb5, 0x6e, 0xfc, 0x1c, 0xe8, 0x6b, 0x9e, 0xa2, 0x60,
	0x8f, 0xc1, 0xff, 0x84, 0xdf, 0x42, 0x32, 0x27, 0x8b, 0xc1, 0x3a, 0xb8, 0xb9, 0x3b, 0xee, 0x25,
	0x46, 0x60, 0x33, 0xa0, 0x9f, 0xb9, 0xb8, 0xc6, 0xd0, 0xdb, 0x71, 0x5a, 0x29, 0x7e, 0x03, 0x47,
	0x67, 0xe2, 0x5a, 0x69, 0xac, 0xd9, 0x0c, 0xbc, 0x22, 0xb7, 0x5f, 0x07, 0x6b, 0x30, 0x4c, 0x73,
	0x77, 0xec, 0x9d, 0x6f, 0x12, 0xaf, 0xc8, 0xd9, 0x13, 0x18, 0x6e, 0xf9, 0xd7, 0x04, 0x2b, 0x51,
	0x64, 0x5c, 0xd9, 0xa0, 0xb1, 0x0b, 0xda, 0x35, 0xe2, 0x35, 0x04, 0x17, 0x78, 0x20, 0x2b, 0x82,
	0x23, 0xa5, 0x65, 0x8d, 0xe7, 0x1b, 0x9b, 0x13, 0xb8, 0x9c, 0x4e, 0x8c, 0x5f, 0xc1, 0xe0, 0x0c,
	0x85, 0x78, 0x59, 0xc9, 0xec, 0xa3, 0x81, 0x33, 0x59, 0x7e, 0x78, 0x8f, 0xb5, 0x4b, 0x73, 0xb0,
	0x13, 0xad, 0x8f, 0x42, 0x18, 0x7f, 0x2f, 0xcc, 0x89, 0xf1, 0x0f, 0x02, 0x81, 0x49, 0xbb, 0xb7,
	0xd1, 0x14, 0xa8, 0xd2, 0xbc, 0xd6, 0x36, 0x62, 0x94, 0xb4, 0x1b, 0x36, 0x01, 0x1f, 0xcb, 0x3c,
	0xf4, 0xad, 0x66, 0x96, 0xec, 0x14, 0x28, 0x9a, 0x56, 0x61, 0x30, 0x27, 0x8b, 0xe1, 0xea, 0xd1,
	0xd2, 0xbd, 0xd2, 0xbf, 0xba, 0xdd, 0xdd, 0x5a, 0x8a, 0x2d, 0x80, 0x56, 0x88, 0xb5, 0x0a, 0xe9,
	0xdc, 0x5f, 0x0c, 0x57, 0xa3, 0x0e, 0x37, 0x37, 0x64, 0x49, 0x92, 0xb4, 0x40, 0xfc, 0x93, 0x00,
	0xbd, 0x34, 0xe3, 0x1f, 0xba, 0x38, 0x9e, 0xe7, 0x35, 0x2a, 0xb5, 0xf7, 0x92, 0x9d, 0xc8, 0x9e,
	0x42, 0x5f, 0xf0, 0x54, 0xa0, 0x0a, 0x7d, 0x7b, 0xe0, 0xb8, 0x3b, 0xd0, 0xfe, 0x1e, 0x8e, 0x76,
	0x08, 0x5b, 0xda, 0x99, 0x35, 0xda, 0x59, 0x1e, 0xae, 0x58, 0xc7, 0xda, 0x1a, 0x97, 0xc6, 0xe9,
	0x86, 0xb1, 0x18, 0x3b, 0x81, 0x71, 0x26, 0x0a, 0x2c, 0xf5, 0x0b, 0x57, 0x81, 0xee, 0x54, 0xd8,
	0xb7, 0x4e, 0x4e, 0x01, 0xfe, 0xc7, 0xb0, 0x3e, 0x78, 0xef, 0x2e, 0x26, 0x3d, 0xf6, 0x00, 0x82,
	0x8d, 0xfc, 0x52, 0x4e, 0x08, 0x1b, 0xc3, 0xe0, 0xad, 0xdc, 0xa6, 0x4a, 0xcb, 0x12, 0x27, 0xde,
	0x7a, 0x7a, 0xfb, 0x3b, 0xea, 0xdd, 0x34, 0x11, 0xb9, 0x6d, 0x22, 0xf2, 0xab, 0x89, 0xc8, 0xf7,
	0x3f, 0x51, 0xef, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0xf3, 0x04, 0x49, 0x03, 0x03, 0x00,
	0x00,
}

func (m *Label) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Label) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Label) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Cluster) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Cluster) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Cluster) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Peer) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Peer) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Peer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CellEpoch) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *CellEpoch) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *CellEpoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Cell) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Cell) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Cell) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Store) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Store) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Store) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintMetapb(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Label) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Cluster) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Peer) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CellEpoch) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Cell) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Store) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovMetapb(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozMetapb(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Label) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Cluster) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Peer) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CellEpoch) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Cell) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Store) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipMetapb(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthMetapb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetapb   = fmt.Errorf("proto: integer overflow")
)
