// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: errorpb.proto

package errorpb

import (
	"fmt"
	"math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"

	metapb "github.com/deepfabric/elasticell/pkg/pb/metapb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotLeader struct {
	CellID               uint64      `protobuf:"varint,1,opt,name=cellID" json:"cellID"`
	Leader               metapb.Peer `protobuf:"bytes,2,opt,name=leader" json:"leader"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NotLeader) Reset()                    { _ = "STUB: not implemented"; return }
func (m *NotLeader) String() string            { _ = "STUB: not implemented"; return "" }
func (*NotLeader) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*NotLeader) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *NotLeader) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NotLeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NotLeader) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NotLeader) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NotLeader) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NotLeader proto.InternalMessageInfo

func (m *NotLeader) GetCellID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *NotLeader) GetLeader() metapb.Peer { _ = "STUB: not implemented"; return *new(metapb.Peer) }

type StoreNotMatch struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreNotMatch) Reset()                    { _ = "STUB: not implemented"; return }
func (m *StoreNotMatch) String() string            { _ = "STUB: not implemented"; return "" }
func (*StoreNotMatch) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*StoreNotMatch) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *StoreNotMatch) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreNotMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StoreNotMatch) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StoreNotMatch) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StoreNotMatch) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StoreNotMatch proto.InternalMessageInfo

type CellNotFound struct {
	CellID               uint64   `protobuf:"varint,1,opt,name=cellID" json:"cellID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellNotFound) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CellNotFound) String() string            { _ = "STUB: not implemented"; return "" }
func (*CellNotFound) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CellNotFound) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CellNotFound) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CellNotFound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CellNotFound) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CellNotFound) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CellNotFound) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CellNotFound proto.InternalMessageInfo

func (m *CellNotFound) GetCellID() uint64 { _ = "STUB: not implemented"; return 0 }

type KeyNotInCell struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	CellID               uint64   `protobuf:"varint,2,opt,name=cellID" json:"cellID"`
	StartKey             []byte   `protobuf:"bytes,3,opt,name=startKey" json:"startKey,omitempty"`
	EndKey               []byte   `protobuf:"bytes,4,opt,name=endKey" json:"endKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyNotInCell) Reset()                    { _ = "STUB: not implemented"; return }
func (m *KeyNotInCell) String() string            { _ = "STUB: not implemented"; return "" }
func (*KeyNotInCell) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*KeyNotInCell) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *KeyNotInCell) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *KeyNotInCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *KeyNotInCell) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *KeyNotInCell) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *KeyNotInCell) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_KeyNotInCell proto.InternalMessageInfo

func (m *KeyNotInCell) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *KeyNotInCell) GetCellID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *KeyNotInCell) GetStartKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *KeyNotInCell) GetEndKey() []byte { _ = "STUB: not implemented"; return nil }

type StaleEpoch struct {
	NewCells             []metapb.Cell `protobuf:"bytes,1,rep,name=newCells" json:"newCells"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StaleEpoch) Reset()                    { _ = "STUB: not implemented"; return }
func (m *StaleEpoch) String() string            { _ = "STUB: not implemented"; return "" }
func (*StaleEpoch) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*StaleEpoch) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *StaleEpoch) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StaleEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StaleEpoch) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StaleEpoch) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StaleEpoch) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StaleEpoch proto.InternalMessageInfo

func (m *StaleEpoch) GetNewCells() []metapb.Cell { _ = "STUB: not implemented"; return nil }

type ServerIsBusy struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerIsBusy) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ServerIsBusy) String() string            { _ = "STUB: not implemented"; return "" }
func (*ServerIsBusy) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ServerIsBusy) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ServerIsBusy) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ServerIsBusy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerIsBusy) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ServerIsBusy) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ServerIsBusy) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ServerIsBusy proto.InternalMessageInfo

type StaleCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaleCommand) Reset()                    { _ = "STUB: not implemented"; return }
func (m *StaleCommand) String() string            { _ = "STUB: not implemented"; return "" }
func (*StaleCommand) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*StaleCommand) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *StaleCommand) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StaleCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StaleCommand) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StaleCommand) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StaleCommand) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StaleCommand proto.InternalMessageInfo

type RaftEntryTooLarge struct {
	CellID               uint64   `protobuf:"varint,1,opt,name=cellID" json:"cellID"`
	EntrySize            uint64   `protobuf:"varint,2,opt,name=entrySize" json:"entrySize"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftEntryTooLarge) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RaftEntryTooLarge) String() string            { _ = "STUB: not implemented"; return "" }
func (*RaftEntryTooLarge) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftEntryTooLarge) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftEntryTooLarge) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftEntryTooLarge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftEntryTooLarge) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftEntryTooLarge) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftEntryTooLarge) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftEntryTooLarge proto.InternalMessageInfo

func (m *RaftEntryTooLarge) GetCellID() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *RaftEntryTooLarge) GetEntrySize() uint64 { _ = "STUB: not implemented"; return 0 }

type Error struct {
	Message              string             `protobuf:"bytes,1,opt,name=message" json:"message"`
	NotLeader            *NotLeader         `protobuf:"bytes,2,opt,name=notLeader" json:"notLeader,omitempty"`
	CellNotFound         *CellNotFound      `protobuf:"bytes,3,opt,name=cellNotFound" json:"cellNotFound,omitempty"`
	KeyNotInCell         *KeyNotInCell      `protobuf:"bytes,4,opt,name=KeyNotInCell" json:"KeyNotInCell,omitempty"`
	StaleEpoch           *StaleEpoch        `protobuf:"bytes,5,opt,name=staleEpoch" json:"staleEpoch,omitempty"`
	ServerIsBusy         *ServerIsBusy      `protobuf:"bytes,6,opt,name=serverIsBusy" json:"serverIsBusy,omitempty"`
	StaleCommand         *StaleCommand      `protobuf:"bytes,7,opt,name=staleCommand" json:"staleCommand,omitempty"`
	StoreNotMatch        *StoreNotMatch     `protobuf:"bytes,8,opt,name=storeNotMatch" json:"storeNotMatch,omitempty"`
	RaftEntryTooLarge    *RaftEntryTooLarge `protobuf:"bytes,9,opt,name=raftEntryTooLarge" json:"raftEntryTooLarge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Error) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Error) String() string            { _ = "STUB: not implemented"; return "" }
func (*Error) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Error) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Error) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Error) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Error) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Error) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string { _ = "STUB: not implemented"; return "" }

func (m *Error) GetNotLeader() *NotLeader { _ = "STUB: not implemented"; return nil }

func (m *Error) GetCellNotFound() *CellNotFound { _ = "STUB: not implemented"; return nil }

func (m *Error) GetKeyNotInCell() *KeyNotInCell { _ = "STUB: not implemented"; return nil }

func (m *Error) GetStaleEpoch() *StaleEpoch { _ = "STUB: not implemented"; return nil }

func (m *Error) GetServerIsBusy() *ServerIsBusy { _ = "STUB: not implemented"; return nil }

func (m *Error) GetStaleCommand() *StaleCommand { _ = "STUB: not implemented"; return nil }

func (m *Error) GetStoreNotMatch() *StoreNotMatch { _ = "STUB: not implemented"; return nil }

func (m *Error) GetRaftEntryTooLarge() *RaftEntryTooLarge { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*NotLeader)(nil), "errorpb.NotLeader")
	proto.RegisterType((*StoreNotMatch)(nil), "errorpb.StoreNotMatch")
	proto.RegisterType((*CellNotFound)(nil), "errorpb.CellNotFound")
	proto.RegisterType((*KeyNotInCell)(nil), "errorpb.KeyNotInCell")
	proto.RegisterType((*StaleEpoch)(nil), "errorpb.StaleEpoch")
	proto.RegisterType((*ServerIsBusy)(nil), "errorpb.ServerIsBusy")
	proto.RegisterType((*StaleCommand)(nil), "errorpb.StaleCommand")
	proto.RegisterType((*RaftEntryTooLarge)(nil), "errorpb.RaftEntryTooLarge")
	proto.RegisterType((*Error)(nil), "errorpb.Error")
}

func init() { proto.RegisterFile("errorpb.proto", fileDescriptor_390aa86757fd1154) }

var fileDescriptor_390aa86757fd1154 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x86, 0xb3, 0x4d, 0x9a, 0x64, 0x4f, 0x37, 0x6a, 0xa7, 0xb5, 0x0c, 0x41, 0xd6, 0x30, 0x57,
	0x45, 0x24, 0x85, 0x5e, 0x08, 0x82, 0x20, 0xa4, 0x46, 0x08, 0xad, 0x8b, 0x24, 0xf6, 0x01, 0xa6,
	0xc9, 0x31, 0x15, 0x37, 0x3b, 0x61, 0x66, 0xaa, 0xac, 0x4f, 0xe2, 0x73, 0xf8, 0x14, 0xbd, 0xec,
	0x13, 0x88, 0xc6, 0x17, 0x91, 0x99, 0xcc, 0x6e, 0x26, 0x89, 0xd8, 0xab, 0xcc, 0x9c, 0xf3, 0xff,
	0xdf, 0xc9, 0xcc, 0x3f, 0x0b, 0x2d, 0x94, 0x52, 0xc8, 0xf9, 0x55, 0x77, 0x2e, 0x85, 0x16, 0xa4,
	0xe1, 0xb6, 0xed, 0x83, 0x19, 0x6a, 0x3e, 0xbf, 0x3a, 0x59, 0xfe, 0x2c, 0xbb, 0xed, 0xc3, 0xa9,
	0x98, 0x0a, 0xbb, 0x3c, 0x31, 0xab, 0x65, 0x95, 0x5d, 0x42, 0x98, 0x08, 0x7d, 0x81, 0x7c, 0x82,
	0x92, 0x3c, 0x81, 0xfa, 0x18, 0xd3, 0x74, 0xf0, 0x86, 0x06, 0x9d, 0xe0, 0xb8, 0xd6, 0xab, 0xdd,
	0xfe, 0x7c, 0x5a, 0x19, 0xba, 0x1a, 0x79, 0x06, 0xf5, 0xd4, 0xea, 0xe8, 0x4e, 0x27, 0x38, 0xde,
	0x3b, 0x8d, 0xba, 0x8e, 0xff, 0x1e, 0x51, 0x16, 0xda, 0xa5, 0x82, 0x3d, 0x84, 0xd6, 0x48, 0x0b,
	0x89, 0x89, 0xd0, 0xef, 0xb8, 0x1e, 0x5f, 0xb3, 0xe7, 0x10, 0x9d, 0x61, 0x9a, 0x26, 0x42, 0xbf,
	0x15, 0x37, 0xd9, 0xe4, 0xff, 0xa3, 0x98, 0x84, 0xe8, 0x1c, 0xf3, 0x44, 0xe8, 0x41, 0x66, 0x5c,
	0xe4, 0x11, 0x54, 0x3f, 0x63, 0x6e, 0xa5, 0xd1, 0xd0, 0x2c, 0x3d, 0xff, 0xce, 0x3f, 0xfe, 0x6a,
	0x1b, 0x9a, 0x4a, 0x73, 0xa9, 0xcf, 0x31, 0xa7, 0x55, 0x6b, 0x2a, 0xf7, 0xe4, 0x08, 0xea, 0x98,
	0x4d, 0x4c, 0xa7, 0x66, 0x3b, 0x6e, 0xc7, 0x5e, 0x01, 0x8c, 0x34, 0x4f, 0xb1, 0x3f, 0x17, 0xe3,
	0x6b, 0xd2, 0x85, 0x66, 0x86, 0x5f, 0xcd, 0x70, 0x45, 0x83, 0x4e, 0xd5, 0x3f, 0xae, 0x29, 0xba,
	0x79, 0xa5, 0x86, 0x3d, 0x80, 0x68, 0x84, 0xf2, 0x0b, 0xca, 0x81, 0xea, 0xdd, 0xa8, 0xdc, 0xee,
	0x0d, 0xed, 0x4c, 0xcc, 0x66, 0x3c, 0x9b, 0xb0, 0x4b, 0xd8, 0x1f, 0xf2, 0x8f, 0xba, 0x9f, 0x69,
	0x99, 0x7f, 0x10, 0xe2, 0x82, 0xcb, 0x29, 0xde, 0x73, 0xdf, 0x0c, 0x42, 0x34, 0xf2, 0xd1, 0xa7,
	0x6f, 0xb8, 0x76, 0xca, 0x55, 0x99, 0xfd, 0xa8, 0xc1, 0x6e, 0xdf, 0xa4, 0x4e, 0x62, 0x68, 0xcc,
	0x50, 0x29, 0x3e, 0x45, 0x0b, 0x0b, 0x9d, 0xb6, 0x28, 0x92, 0x17, 0x10, 0x66, 0x45, 0xd0, 0x2e,
	0x40, 0xd2, 0x2d, 0xde, 0x4f, 0xf9, 0x04, 0xac, 0x2b, 0x18, 0xae, 0xa4, 0xe4, 0x35, 0x44, 0x63,
	0x2f, 0x38, 0x7b, 0x9d, 0x7b, 0xa7, 0x8f, 0x4b, 0xab, 0x9f, 0xaa, 0x73, 0xaf, 0x19, 0x0c, 0xc0,
	0xcf, 0xd2, 0xde, 0xba, 0x0f, 0xf0, 0x9b, 0x05, 0x60, 0x2d, 0xfc, 0x97, 0x00, 0xaa, 0x0c, 0x86,
	0xee, 0x5a, 0xfb, 0x41, 0x69, 0x5f, 0x65, 0xe6, 0xcc, 0x9e, 0xd8, 0xcc, 0x56, 0x5e, 0x2a, 0xb4,
	0xbe, 0x31, 0xdb, 0x8f, 0xac, 0x98, 0xed, 0x1b, 0x2c, 0xc0, 0x8b, 0x91, 0x36, 0x36, 0x01, 0x5e,
	0xb3, 0x04, 0x78, 0x35, 0xd2, 0x83, 0x96, 0xf2, 0x3f, 0x04, 0xda, 0xb4, 0x84, 0x23, 0x8f, 0xe0,
	0x75, 0x1d, 0x62, 0xdd, 0x42, 0x12, 0xd8, 0x97, 0x9b, 0x6f, 0x87, 0x86, 0x96, 0xd3, 0x2e, 0x39,
	0x5b, 0xaf, 0xcb, 0xb1, 0xb6, 0xad, 0xbd, 0xc3, 0xbb, 0xdf, 0x71, 0xe5, 0x76, 0x11, 0x07, 0x77,
	0x8b, 0x38, 0xf8, 0xb5, 0x88, 0x83, 0xef, 0x7f, 0xe2, 0xca, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x07, 0xdb, 0xe8, 0x46, 0x4d, 0x04, 0x00, 0x00,
}

func (m *NotLeader) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *NotLeader) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *NotLeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreNotMatch) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StoreNotMatch) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreNotMatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CellNotFound) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CellNotFound) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CellNotFound) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *KeyNotInCell) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *KeyNotInCell) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *KeyNotInCell) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StaleEpoch) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *StaleEpoch) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *StaleEpoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerIsBusy) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerIsBusy) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerIsBusy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StaleCommand) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StaleCommand) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StaleCommand) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftEntryTooLarge) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftEntryTooLarge) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RaftEntryTooLarge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Error) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Error) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintErrorpb(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *NotLeader) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreNotMatch) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CellNotFound) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *KeyNotInCell) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StaleEpoch) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerIsBusy) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StaleCommand) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RaftEntryTooLarge) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Error) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovErrorpb(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozErrorpb(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NotLeader) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreNotMatch) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CellNotFound) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *KeyNotInCell) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StaleEpoch) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ServerIsBusy) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StaleCommand) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftEntryTooLarge) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Error) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipErrorpb(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthErrorpb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowErrorpb   = fmt.Errorf("proto: integer overflow")
)
